# 🎓 SQL'e Giriş: YBS Öğrencileri için Kapsamlı SQL Dersi

---

<div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 15px; color: white; margin: 20px 0;">
    <h2 style="color: white; margin-top: 0;">🎯 Ders Hedefleri</h2>
    <ul style="font-size: 16px; line-height: 1.8;">
        <li><strong>SQL'in temel mantığını</strong> ve veritabanı düşünce yapısını kavramak</li>
        <li><strong>SELECT, FROM, WHERE, LIMIT</strong> komutlarıyla veri çekmeyi öğrenmek</li>
        <li><strong>YBS senaryolarında</strong> SQL'i nasıl kullanacağınızı görmek</li>
        <li><strong>Python ile SQL</strong> entegrasyonunu uygulamalı öğrenmek</li>
    </ul>
</div>

**Hazırlayan:** Veri Bilimi & Makine Öğrenmesi Bootcamp 2026  
**Tarih:** 18 Ocak 2026  
**Seviye:** Başlangıç → İleri

---

# 📚 ADIM 1: Temel Kavramlar ve Giriş

## 🤔 SQL Nedir ve Neden Öğreniyoruz?

<div style="background-color: #FFF4E6; padding: 20px; border-left: 5px solid #FF9800; border-radius: 10px; margin: 15px 0;">
    <h3 style="color: #E65100; margin-top: 0;">💡 Tanım</h3>
    <p style="font-size: 16px; line-height: 1.6;">
        <strong>SQL (Structured Query Language)</strong>, veritabanlarıyla "konuşmak" için geliştirilmiş evrensel bir dildir. 
        Veritabanında tutulmuş verileri <strong>düzenli biçimde çekebilmek</strong>, yani ihtiyaç duyduğumuz veriyi 
        <strong>sorgulayarak ekrana getirmek</strong> için kullanırız.
    </p>
</div>

### 🎯 Neden SQL Öğrenmeliyiz?

```mermaid
graph LR
    A["🎓 Eğitimde<br/>Hazır Veri Setleri"] --> B["📊 Kaggle, UCI<br/>CSV Dosyaları"]
    C["💼 İş Hayatında<br/>Gerçek Veri"] --> D["🗄️ Veritabanları<br/>SQL Server, PostgreSQL"]
    D --> E["🔍 SQL ile<br/>Veri Çekme"]
    E --> F["📈 Analiz ve<br/>Makine Öğrenmesi"]
    
    style A fill:#E3F2FD,stroke:#1976D2,stroke-width:2px
    style C fill:#FFF3E0,stroke:#F57C00,stroke-width:2px
    style E fill:#E8F5E9,stroke:#388E3C,stroke-width:3px
    style F fill:#F3E5F5,stroke:#7B1FA2,stroke-width:2px
```

<div style="background-color: #E8F5E9; padding: 20px; border-radius: 10px; margin: 20px 0;">
    <h3 style="color: #2E7D32;">🎯 Gerçek Hayat Senaryosu</h3>
    <p style="font-size: 15px; line-height: 1.7;">
        <strong>Durum:</strong> Bir e-ticaret şirketinde veri analistsiniz. Pazarlama ekibi sizden <em>"Son 3 ayda 1000 TL üzeri alışveriş yapan İstanbul'daki müşteri listesini"</em> istiyor.
    </p>
    <p style="font-size: 15px; line-height: 1.7; margin-bottom: 0;">
        <strong>Çözüm:</strong> Bu veriyi CSV dosyasında bulamazsınız! Şirketin veritabanına <strong>SQL sorgusu</strong> yazarak çekmeniz gerekir. İşte SQL'in gücü burada ortaya çıkar! 💪
    </p>
</div>

---

## 🗄️ Veritabanı Nedir? YBS Mantığıyla Düşünme

<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 20px 0;">
    <div style="background-color: #E3F2FD; padding: 20px; border-radius: 10px; border-top: 4px solid #1976D2;">
        <h3 style="color: #1565C0; margin-top: 0;">📊 SQL Veritabanları</h3>
        <ul style="font-size: 14px; line-height: 1.6;">
            <li><strong>Tablo yapısı</strong> (Excel benzeri)</li>
            <li><strong>İlişkisel</strong> (tablolar arası bağlantılar)</li>
            <li><strong>ACID uyumlu</strong> (güvenli işlemler)</li>
            <li>Örnekler: MySQL, PostgreSQL, SQL Server, SQLite</li>
        </ul>
    </div>
    <div style="background-color: #FFF3E0; padding: 20px; border-radius: 10px; border-top: 4px solid #F57C00;">
        <h3 style="color: #E65100; margin-top: 0;">🔥 NoSQL Veritabanları</h3>
        <ul style="font-size: 14px; line-height: 1.6;">
            <li><strong>Anahtar-Değer</strong> mantığı</li>
            <li><strong>Esnek yapı</strong> (şema yok)</li>
            <li><strong>Yüksek hız</strong> (büyük veri için)</li>
            <li>Örnekler: MongoDB, Redis, Cassandra</li>
        </ul>
    </div>
</div>

### 📊 İlişkisel Veritabanı: Excel Benzetmesi

<div style="background-color: #F3E5F5; padding: 20px; border-radius: 10px; margin: 20px 0;">
    <h4 style="color: #6A1B9A; margin-top: 0;">🎯 Kritik Kavram: Tablo = Excel Sayfası</h4>
    <p style="font-size: 15px; line-height: 1.7;">
        İlişkisel veritabanında veri <strong>tablo mantığıyla</strong> tutulur:
    </p>
    <ul style="font-size: 15px; line-height: 1.7;">
        <li><strong>Satırlar:</strong> Kayıtlar (her bir müşteri, ürün, sipariş...)</li>
        <li><strong>Sütunlar:</strong> Özellikler/Alanlar (id, isim, fiyat, tarih...)</li>
        <li><strong>İlişkiler:</strong> Tablolar arası bağlantılar (foreign key ile)</li>
    </ul>
</div>

### 🛒 YBS Klasik Örnek: E-Ticaret Sistemi

```mermaid
erDiagram
    CUSTOMERS ||--o{ ORDERS : "yapar"
    ORDERS ||--|{ ORDER_ITEMS : "içerir"
    PRODUCTS ||--o{ ORDER_ITEMS : "bulunur"
    
    CUSTOMERS {
        int customer_id PK
        string email
        string name
        string city
        int age
    }
    
    PRODUCTS {
        int product_id PK
        string name
        decimal price
        string category
    }
    
    ORDERS {
        int order_id PK
        int customer_id FK
        date order_date
        decimal total_amount
    }
    
    ORDER_ITEMS {
        int item_id PK
        int order_id FK
        int product_id FK
        int quantity
        decimal price
    }
```

<div style="background-color: #FFF9C4; padding: 20px; border-left: 5px solid #FBC02D; border-radius: 10px; margin: 20px 0;">
    <h3 style="color: #F57F17; margin-top: 0;">🔑 İlişkisel Düşünmenin Gücü</h3>
    <p style="font-size: 15px; line-height: 1.7;">
        <strong>❌ YANLIŞ YOL:</strong> Sipariş tablosunda müşterinin tüm bilgilerini (isim, email, adres...) tekrar tekrar yazmak.
    </p>
    <p style="font-size: 15px; line-height: 1.7; margin-bottom: 0;">
        <strong>✅ DOĞRU YOL:</strong> Sipariş tablosunda sadece <code>customer_id</code> tutmak. Müşteri detaylarını gerektiğinde <strong>CUSTOMERS</strong> tablosundan çekmek.
    </p>
    <p style="font-size: 15px; line-height: 1.7; margin-bottom: 0; margin-top: 15px;">
        <strong>🎯 Avantajlar:</strong>
    </p>
    <ul style="font-size: 15px; line-height: 1.7; margin-bottom: 0;">
        <li>✨ Veri tekrarı yok (disk tasarrufu)</li>
        <li>🔄 Güncelleme kolaylığı (müşteri bilgisi tek yerden değişir)</li>
        <li>🎯 Veri tutarlılığı (çelişkili veri olmaz)</li>
    </ul>
</div>

---

## 🗃️ SQLite Nedir ve Neden Kullanıyoruz?

<div style="background-color: #E0F2F1; padding: 20px; border-radius: 10px; margin: 20px 0;">
    <h3 style="color: #00695C; margin-top: 0;">📱 SQLite Özellikleri</h3>
    <ul style="font-size: 15px; line-height: 1.7;">
        <li><strong>🪶 Hafif:</strong> Tek dosya, kurulum gerektirmez</li>
        <li><strong>⚡ Hızlı:</strong> Küçük-orta ölçekli projeler için ideal</li>
        <li><strong>📱 Taşınabilir:</strong> Android/iOS uygulamalarında kullanılır</li>
        <li><strong>🎓 Öğretici:</strong> SQL mantığını öğrenmek için mükemmel</li>
        <li><strong>🔄 Uyumlu:</strong> Öğrendiğiniz komutlar MySQL, PostgreSQL'de de çalışır</li>
    </ul>
</div>

```mermaid
graph TD
    A["🎯 SQL Öğrenme Hedefi"] --> B["📚 SQLite ile Başla"]
    B --> C{"Temel SQL Komutları"}
    C --> D["SELECT"]
    C --> E["FROM"]
    C --> F["WHERE"]
    C --> G["LIMIT"]
    D --> H["🚀 İleri SQL"]
    E --> H
    F --> H
    G --> H
    H --> I["💼 MySQL/PostgreSQL"]
    H --> J["☁️ SQL Server"]
    I --> K["⭐ Uzman Seviye"]
    J --> K
    
    style A fill:#FFE082,stroke:#F57C00,stroke-width:3px
    style B fill:#A5D6A7,stroke:#388E3C,stroke-width:2px
    style C fill:#90CAF9,stroke:#1976D2,stroke-width:2px
    style H fill:#CE93D8,stroke:#7B1FA2,stroke-width:2px
    style K fill:#FFAB91,stroke:#D84315,stroke-width:3px
```

---

## 🎴 FLASHCARD: Temel Kavramlar

In [2]:
# Flashcard'ları güzel görüntülemek için HTML kullanıyoruz
# Dark mode pastel tonlar ile mükemmel kontrast!
from IPython.display import HTML, display

flashcards_html = """
<div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin: 20px 0;">
    
   <div style="background: linear-gradient(135deg, #5E35B1 0%, #4A148C 100%); padding: 20px; border-radius: 10px; color: white; min-height: 150px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <h4 style="color: white; margin-top: 0; font-size: 16px;">🎯 SQL</h4>
        <p style="font-size: 14px; line-height: 1.6; margin-bottom: 0;">
            <strong>Structured Query Language</strong><br/>
            Veritabanlarıyla iletişim kurmak için kullanılan standart dil. Veri çekme, ekleme, güncelleme, silme işlemleri için kullanılır.
        </p>
    </div>
    
    <div style="background: linear-gradient(135deg, #C2185B 0%, #880E4F 100%); padding: 20px; border-radius: 10px; color: white; min-height: 150px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <h4 style="color: white; margin-top: 0; font-size: 16px;">📊 Veritabanı</h4>
        <p style="font-size: 14px; line-height: 1.6; margin-bottom: 0;">
            Verilerin <strong>organize edilmiş</strong> ve <strong>kalıcı olarak saklandığı</strong> dijital depo. Tablolar, kayıtlar ve ilişkiler içerir.
        </p>
    </div>
    
    <div style="background: linear-gradient(135deg, #1976D2 0%, #0D47A1 100%); padding: 20px; border-radius: 10px; color: white; min-height: 150px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <h4 style="color: white; margin-top: 0; font-size: 16px;">🔗 İlişkisel DB</h4>
        <p style="font-size: 14px; line-height: 1.6; margin-bottom: 0;">
            Verileri <strong>tablolar</strong> halinde tutan ve tablolar arasında <strong>ilişkiler</strong> kurabilen veritabanı sistemi. Excel'e benzer yapı.
        </p>
    </div>
    
    <div style="background: linear-gradient(135deg, #00897B 0%, #004D40 100%); padding: 20px; border-radius: 10px; color: white; min-height: 150px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <h4 style="color: white; margin-top: 0; font-size: 16px;">🗂️ Tablo</h4>
        <p style="font-size: 14px; line-height: 1.6; margin-bottom: 0;">
            Satırlar (kayıtlar) ve sütunlar (alanlar) içeren veri yapısı. Her tablo belirli bir varlığı temsil eder (müşteriler, ürünler, siparişler...).
        </p>
    </div>
    
    <div style="background: linear-gradient(135deg, #D84315 0%, #BF360C 100%); padding: 20px; border-radius: 10px; color: white; min-height: 150px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <h4 style="color: white; margin-top: 0; font-size: 16px;">🔑 Primary Key (PK)</h4>
        <p style="font-size: 14px; line-height: 1.6; margin-bottom: 0;">
            Her satırı <strong>benzersiz</strong> şekilde tanımlayan kolon. Örnek: <code style="background: rgba(255,255,255,0.2); padding: 2px 6px; border-radius: 3px;">customer_id</code>, <code style="background: rgba(255,255,255,0.2); padding: 2px 6px; border-radius: 3px;">order_id</code>. NULL olamaz, tekil olmalı.
        </p>
    </div>
    
    <div style="background: linear-gradient(135deg, #7B1FA2 0%, #4A148C 100%); padding: 20px; border-radius: 10px; color: white; min-height: 150px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <h4 style="color: white; margin-top: 0; font-size: 16px;">🔗 Foreign Key (FK)</h4>
        <p style="font-size: 14px; line-height: 1.6; margin-bottom: 0;">
            Başka bir tablonun Primary Key'ini referans eden kolon. <strong>Tablolar arası ilişki</strong> kurar. Örnek: Orders tablosunda <code style="background: rgba(255,255,255,0.2); padding: 2px 6px; border-radius: 3px;">customer_id</code>.
        </p>
    </div>
    
</div>
"""

display(HTML(flashcards_html))

---

<div style="background-color: #E8EAF6; padding: 20px; border-radius: 10px; text-align: center; margin: 30px 0;">
    <h2 style="color: #3F51B5; margin-top: 0;">🎉 Adım 1 Tamamlandı!</h2>
    <p style="font-size: 16px; color: #5C6BC0;">
        Artık SQL'in temellerini ve zihinsel modelini kavradınız.<br/>
        Hadi bir sonraki adımda kod yazmaya başlayalım! 🚀
    </p>
</div>

---
---

# 🔧 ADIM 2: Çalışma Ortamı ve Veri Seti Hazırlığı

<div style="background: linear-gradient(135deg, #FF6B6B 0%, #C92A2A 100%); padding: 25px; border-radius: 15px; color: white; margin: 20px 0;">
    <h2 style="color: white; margin-top: 0;">🎯 Bu Adımda Neler Yapacağız?</h2>
    <ul style="font-size: 16px; line-height: 1.8;">
        <li>✅ Python ile SQLite bağlantısı kuracağız</li>
        <li>✅ Gerçekçi bir YBS e-ticaret veri seti oluşturacağız</li>
        <li>✅ 4 tablo (Customers, Products, Orders, Order_Items) hazırlayacağız</li>
        <li>✅ İlişkisel yapıyı pratikte göreceğiz</li>
    </ul>
</div>

## 📦 Gerekli Kütüphaneleri İçe Aktarma

Python'da SQLite ile çalışmak için **sqlite3** modülünü kullanacağız. Bu modül Python'un standart kütüphanesinde gelir, ek kurulum gerekmez!

In [3]:
# Gerekli kütüphaneleri içe aktarıyoruz
import sqlite3  # SQLite veritabanı ile çalışmak için
import pandas as pd  # Veriyi tablo formatında görmek için
from datetime import datetime, timedelta  # Tarih işlemleri için
import random  # Rastgele veri üretmek için
from IPython.display import display, HTML  # Güzel çıktılar için

# Başarılı import mesajı
print("✅ Tüm kütüphaneler başarıyla yüklendi!")
print(f"📅 Bugünün tarihi: {datetime.now().strftime('%d %B %Y')}")
print(f"🐍 Python ile SQLite bağlantısına hazırız!")

✅ Tüm kütüphaneler başarıyla yüklendi!
📅 Bugünün tarihi: 18 January 2026
🐍 Python ile SQLite bağlantısına hazırız!

---

## 🗄️ SQLite Veritabanı Oluşturma ve Bağlantı Kurma

SQLite'ın en büyük avantajı: **Tek bir dosya olarak çalışır!** Herhangi bir sunucu kurulumu gerektirmez.

In [4]:
# Veritabanı dosyasının adı (yoksa otomatik oluşturulur)
db_name = "eticaret_ybs.db"

# Veritabanına bağlantı oluşturuyoruz
# Eğer dosya yoksa, otomatik olarak oluşturulur
conn = sqlite3.connect(db_name)

# Cursor (imleç) oluşturuyoruz - SQL komutlarını çalıştırmak için
cursor = conn.cursor()

print(f"✅ '{db_name}' veritabanına başarıyla bağlanıldı!")
print(f"📂 Veritabanı dosyası mevcut dizinde oluşturuldu.")
print(f"🔗 Bağlantı aktif ve kullanıma hazır!")

✅ 'eticaret_ybs.db' veritabanına başarıyla bağlanıldı!
📂 Veritabanı dosyası mevcut dizinde oluşturuldu.
🔗 Bağlantı aktif ve kullanıma hazır!

```mermaid
graph LR
    A["🐍 Python Kodu"] -->|sqlite3.connect| B["🔗 Bağlantı Objesi<br/>(conn)"]
    B -->|cursor| C["📍 Cursor Objesi<br/>(cursor)"]
    C -->|SQL Sorguları| D["🗄️ SQLite DB<br/>eticaret_ybs.db"]
    D -->|Sonuçlar| C
    C -->|Veri| A
    
    style A fill:#A5D6A7,stroke:#388E3C,stroke-width:2px
    style B fill:#90CAF9,stroke:#1976D2,stroke-width:2px
    style C fill:#FFD54F,stroke:#F57C00,stroke-width:2px
    style D fill:#CE93D8,stroke:#7B1FA2,stroke-width:3px
```

---

## 🏗️ Tablo Yapılarını Tasarlama: YBS E-Ticaret Senaryosu

<div style="background-color: #E8F5E9; padding: 20px; border-left: 5px solid #4CAF50; border-radius: 10px; margin: 20px 0;">
    <h3 style="color: #2E7D32; margin-top: 0;">💼 İş Senaryosu</h3>
    <p style="font-size: 15px; line-height: 1.7;">
        Türkiye'de faaliyet gösteren bir <strong>e-ticaret şirketi</strong> düşünelim. Bu şirket:
    </p>
    <ul style="font-size: 15px; line-height: 1.7;">
        <li>📦 Elektronik ürünler satıyor</li>
        <li>👥 Farklı şehirlerden müşterileri var</li>
        <li>🛒 Her gün onlarca sipariş alıyor</li>
        <li>📊 Veri analitiği ile karar veriyor</li>
    </ul>
    <p style="font-size: 15px; line-height: 1.7; margin-bottom: 0;">
        <strong>Göreviniz:</strong> Bu şirketin veritabanını oluşturup, SQL ile analizler yapmak!
    </p>
</div>

### 📋 Tablo Yapıları ve İlişkileri

```mermaid
erDiagram
    CUSTOMERS ||--o{ ORDERS : "sipariş_verir"
    ORDERS ||--|{ ORDER_ITEMS : "içerir"
    PRODUCTS ||--o{ ORDER_ITEMS : "satılır"
    
    CUSTOMERS {
        int customer_id PK "🔑 Birincil Anahtar"
        string first_name "İsim"
        string last_name "Soyisim"
        string email "E-posta (unique)"
        string city "Şehir"
        int age "Yaş"
        date registration_date "Kayıt Tarihi"
    }
    
    PRODUCTS {
        int product_id PK "🔑 Birincil Anahtar"
        string name "Ürün Adı"
        string category "Kategori"
        decimal price "Fiyat (TL)"
        int stock "Stok Miktarı"
    }
    
    ORDERS {
        int order_id PK "🔑 Birincil Anahtar"
        int customer_id FK "🔗 Müşteri Ref"
        date order_date "Sipariş Tarihi"
        string status "Durum"
        decimal total_amount "Toplam Tutar"
    }
    
    ORDER_ITEMS {
        int item_id PK "🔑 Birincil Anahtar"
        int order_id FK "🔗 Sipariş Ref"
        int product_id FK "🔗 Ürün Ref"
        int quantity "Adet"
        decimal unit_price "Birim Fiyat"
    }
```

---

## 🛠️ Tabloları Oluşturma (CREATE TABLE)

Şimdi SQL komutlarıyla tablolarımızı oluşturacağız. **CREATE TABLE** komutu tablo yaratmak için kullanılır.

In [5]:
# Eğer tablolar zaten varsa, önce silelim (temiz başlangıç için)
cursor.execute("DROP TABLE IF EXISTS order_items")
cursor.execute("DROP TABLE IF EXISTS orders")
cursor.execute("DROP TABLE IF EXISTS customers")
cursor.execute("DROP TABLE IF EXISTS products")

print("🗑️ Eski tablolar temizlendi (varsa)")
print("📋 Yeni tablolar oluşturuluyor...\n")

🗑️ Eski tablolar temizlendi (varsa)
📋 Yeni tablolar oluşturuluyor...

In [6]:
# 1️⃣ CUSTOMERS (Müşteriler) Tablosu
cursor.execute("""
    CREATE TABLE customers (
        customer_id INTEGER PRIMARY KEY AUTOINCREMENT,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        email TEXT UNIQUE NOT NULL,
        city TEXT NOT NULL,
        age INTEGER,
        registration_date DATE NOT NULL
    )
""")

print("✅ 1. CUSTOMERS tablosu oluşturuldu!")
print("   └─ Kolonlar: customer_id, first_name, last_name, email, city, age, registration_date")

✅ 1. CUSTOMERS tablosu oluşturuldu!
   └─ Kolonlar: customer_id, first_name, last_name, email, city, age, registration_date

In [7]:
# 2️⃣ PRODUCTS (Ürünler) Tablosu
cursor.execute("""
    CREATE TABLE products (
        product_id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        category TEXT NOT NULL,
        price REAL NOT NULL,
        stock INTEGER NOT NULL DEFAULT 0
    )
""")

print("✅ 2. PRODUCTS tablosu oluşturuldu!")
print("   └─ Kolonlar: product_id, name, category, price, stock")

✅ 2. PRODUCTS tablosu oluşturuldu!
   └─ Kolonlar: product_id, name, category, price, stock

In [8]:
# 3️⃣ ORDERS (Siparişler) Tablosu
cursor.execute("""
    CREATE TABLE orders (
        order_id INTEGER PRIMARY KEY AUTOINCREMENT,
        customer_id INTEGER NOT NULL,
        order_date DATE NOT NULL,
        status TEXT NOT NULL,
        total_amount REAL NOT NULL,
        FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
    )
""")

print("✅ 3. ORDERS tablosu oluşturuldu!")
print("   └─ Kolonlar: order_id, customer_id (FK), order_date, status, total_amount")

✅ 3. ORDERS tablosu oluşturuldu!
   └─ Kolonlar: order_id, customer_id (FK), order_date, status, total_amount

In [9]:
# 4️⃣ ORDER_ITEMS (Sipariş Detayları) Tablosu
cursor.execute("""
    CREATE TABLE order_items (
        item_id INTEGER PRIMARY KEY AUTOINCREMENT,
        order_id INTEGER NOT NULL,
        product_id INTEGER NOT NULL,
        quantity INTEGER NOT NULL,
        unit_price REAL NOT NULL,
        FOREIGN KEY (order_id) REFERENCES orders(order_id),
        FOREIGN KEY (product_id) REFERENCES products(product_id)
    )
""")

print("✅ 4. ORDER_ITEMS tablosu oluşturuldu!")
print("   └─ Kolonlar: item_id, order_id (FK), product_id (FK), quantity, unit_price")

# Değişiklikleri kaydet
conn.commit()
print("\n💾 Tüm tablolar veritabanına kaydedildi!")

✅ 4. ORDER_ITEMS tablosu oluşturuldu!
   └─ Kolonlar: item_id, order_id (FK), product_id (FK), quantity, unit_price

💾 Tüm tablolar veritabanına kaydedildi!

---

## 📊 Gerçekçi Veri Ekleme (INSERT INTO)

Şimdi tablolarımıza gerçekçi veriler ekleyeceğiz. **INSERT INTO** komutu veri eklemek için kullanılır.

### 👥 Müşteri Verileri Ekleme

In [10]:
# Türk isimleri ve şehirler ile gerçekçi müşteri verileri
customers_data = [
    ('Ahmet', 'Yılmaz', 'ahmet.yilmaz@gmail.com', 'İstanbul', 28, '2024-01-15'),
    ('Ayşe', 'Demir', 'ayse.demir@hotmail.com', 'Ankara', 35, '2024-02-20'),
    ('Mehmet', 'Kaya', 'mehmet.kaya@yahoo.com', 'İzmir', 42, '2024-01-10'),
    ('Fatma', 'Şahin', 'fatma.sahin@gmail.com', 'İstanbul', 31, '2024-03-05'),
    ('Ali', 'Çelik', 'ali.celik@outlook.com', 'Bursa', 25, '2024-02-14'),
    ('Zeynep', 'Arslan', 'zeynep.arslan@gmail.com', 'Ankara', 29, '2024-01-20'),
    ('Mustafa', 'Yıldız', 'mustafa.yildiz@gmail.com', 'Antalya', 38, '2024-03-12'),
    ('Elif', 'Aydın', 'elif.aydin@hotmail.com', 'İzmir', 26, '2024-02-28'),
    ('Hüseyin', 'Öztürk', 'huseyin.ozturk@gmail.com', 'İstanbul', 45, '2024-01-08'),
    ('Merve', 'Polat', 'merve.polat@yahoo.com', 'Konya', 33, '2024-03-18'),
    ('Emre', 'Kurt', 'emre.kurt@gmail.com', 'Ankara', 27, '2024-02-05'),
    ('Selin', 'Şen', 'selin.sen@hotmail.com', 'İzmir', 30, '2024-01-25'),
    ('Burak', 'Acar', 'burak.acar@gmail.com', 'İstanbul', 36, '2024-03-01'),
    ('Deniz', 'Koç', 'deniz.koc@outlook.com', 'Bursa', 24, '2024-02-10'),
    ('Cem', 'Özdemir', 'cem.ozdemir@gmail.com', 'Antalya', 40, '2024-01-30')
]

# Verileri toplu olarak ekliyoruz
cursor.executemany("""
    INSERT INTO customers (first_name, last_name, email, city, age, registration_date)
    VALUES (?, ?, ?, ?, ?, ?)
""", customers_data)

conn.commit()
print(f"✅ {len(customers_data)} müşteri başarıyla eklendi!")
print("📋 Müşteri listesi: Ahmet, Ayşe, Mehmet, Fatma, Ali ve daha fazlası...")

✅ 15 müşteri başarıyla eklendi!
📋 Müşteri listesi: Ahmet, Ayşe, Mehmet, Fatma, Ali ve daha fazlası...

### 📦 Ürün Verileri Ekleme

In [11]:
# Gerçekçi elektronik ürünler ve fiyatları (TL)
products_data = [
    ('iPhone 15 Pro', 'Telefon', 45999.00, 50),
    ('Samsung Galaxy S24', 'Telefon', 38999.00, 45),
    ('MacBook Air M2', 'Laptop', 52999.00, 30),
    ('Dell XPS 15', 'Laptop', 48999.00, 25),
    ('iPad Air', 'Tablet', 24999.00, 60),
    ('Sony WH-1000XM5', 'Kulaklık', 12999.00, 100),
    ('Apple Watch Series 9', 'Saat', 18999.00, 40),
    ('Samsung Galaxy Buds', 'Kulaklık', 3499.00, 150),
    ('LG 55" OLED TV', 'Televizyon', 35999.00, 20),
    ('PlayStation 5', 'Oyun Konsolu', 21999.00, 35),
    ('Nintendo Switch', 'Oyun Konsolu', 11999.00, 55),
    ('Canon EOS R6', 'Fotoğraf Makinesi', 89999.00, 15),
    ('GoPro Hero 12', 'Aksiyon Kamera', 16999.00, 40),
    ('Dyson V15', 'Elektrikli Süpürge', 22999.00, 25),
    ('Xiaomi Robot Süpürge', 'Robot Süpürge', 8999.00, 50)
]

cursor.executemany("""
    INSERT INTO products (name, category, price, stock)
    VALUES (?, ?, ?, ?)
""", products_data)

conn.commit()
print(f"✅ {len(products_data)} ürün başarıyla eklendi!")
print("📦 Ürün kategorileri: Telefon, Laptop, Tablet, Kulaklık, Saat ve daha fazlası...")

✅ 15 ürün başarıyla eklendi!
📦 Ürün kategorileri: Telefon, Laptop, Tablet, Kulaklık, Saat ve daha fazlası...

### 🛒 Sipariş Verileri Ekleme

In [12]:
# Gerçekçi sipariş verileri (son 3 ay)
orders_data = [
    (1, '2025-11-15', 'Teslim Edildi', 45999.00),
    (2, '2025-11-20', 'Teslim Edildi', 38999.00),
    (3, '2025-12-01', 'Teslim Edildi', 52999.00),
    (1, '2025-12-10', 'Teslim Edildi', 12999.00),
    (4, '2025-12-15', 'Kargoda', 24999.00),
    (5, '2025-12-20', 'Teslim Edildi', 48999.00),
    (6, '2026-01-05', 'Kargoda', 18999.00),
    (7, '2026-01-08', 'Hazırlanıyor', 35999.00),
    (8, '2026-01-10', 'Teslim Edildi', 3499.00),
    (3, '2026-01-12', 'Kargoda', 89999.00),
    (9, '2026-01-13', 'Hazırlanıyor', 21999.00),
    (10, '2026-01-14', 'Teslim Edildi', 16999.00),
    (2, '2026-01-15', 'Kargoda', 11999.00),
    (11, '2026-01-16', 'Hazırlanıyor', 22999.00),
    (12, '2026-01-17', 'Hazırlanıyor', 8999.00),
    (13, '2026-01-17', 'Teslim Edildi', 45999.00),
    (14, '2026-01-18', 'Hazırlanıyor', 24999.00),
    (15, '2026-01-18', 'Hazırlanıyor', 12999.00)
]

cursor.executemany("""
    INSERT INTO orders (customer_id, order_date, status, total_amount)
    VALUES (?, ?, ?, ?)
""", orders_data)

conn.commit()
print(f"✅ {len(orders_data)} sipariş başarıyla eklendi!")
print("🛒 Sipariş durumları: Teslim Edildi, Kargoda, Hazırlanıyor")

✅ 18 sipariş başarıyla eklendi!
🛒 Sipariş durumları: Teslim Edildi, Kargoda, Hazırlanıyor

### 📝 Sipariş Detayları Ekleme

In [13]:
# Her siparişin detayları (hangi üründen kaç adet alındı)
order_items_data = [
    (1, 1, 1, 45999.00),      # Sipariş 1: 1 adet iPhone 15 Pro
    (2, 2, 1, 38999.00),      # Sipariş 2: 1 adet Samsung Galaxy S24
    (3, 3, 1, 52999.00),      # Sipariş 3: 1 adet MacBook Air M2
    (4, 6, 1, 12999.00),      # Sipariş 4: 1 adet Sony Kulaklık
    (5, 5, 1, 24999.00),      # Sipariş 5: 1 adet iPad Air
    (6, 4, 1, 48999.00),      # Sipariş 6: 1 adet Dell XPS 15
    (7, 7, 1, 18999.00),      # Sipariş 7: 1 adet Apple Watch
    (8, 9, 1, 35999.00),      # Sipariş 8: 1 adet LG OLED TV
    (9, 8, 2, 3499.00),       # Sipariş 9: 2 adet Galaxy Buds
    (10, 12, 1, 89999.00),    # Sipariş 10: 1 adet Canon EOS R6
    (11, 10, 1, 21999.00),    # Sipariş 11: 1 adet PS5
    (12, 13, 1, 16999.00),    # Sipariş 12: 1 adet GoPro
    (13, 11, 1, 11999.00),    # Sipariş 13: 1 adet Nintendo Switch
    (14, 14, 1, 22999.00),    # Sipariş 14: 1 adet Dyson
    (15, 15, 1, 8999.00),     # Sipariş 15: 1 adet Xiaomi Robot
    (16, 1, 1, 45999.00),     # Sipariş 16: 1 adet iPhone 15 Pro
    (17, 5, 1, 24999.00),     # Sipariş 17: 1 adet iPad Air
    (18, 6, 1, 12999.00)      # Sipariş 18: 1 adet Sony Kulaklık
]

cursor.executemany("""
    INSERT INTO order_items (order_id, product_id, quantity, unit_price)
    VALUES (?, ?, ?, ?)
""", order_items_data)

conn.commit()
print(f"✅ {len(order_items_data)} sipariş detayı başarıyla eklendi!")
print("📝 Her siparişin ürün detayları kaydedildi!")

✅ 18 sipariş detayı başarıyla eklendi!
📝 Her siparişin ürün detayları kaydedildi!

---

## 🎉 Veritabanı Hazır! Hızlı Kontrol Edelim

In [14]:
# Veritabanı istatistikleri
stats_html = """
<div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin: 20px 0;">
    
    <div style="background: linear-gradient(135deg, #5E35B1 0%, #4A148C 100%); padding: 20px; border-radius: 10px; text-align: center; color: white; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <h3 style="color: white; margin: 0; font-size: 36px;">👥</h3>
        <p style="font-size: 32px; font-weight: bold; margin: 10px 0;">{}</p>
        <p style="font-size: 14px; margin: 0;">Müşteri</p>
    </div>
    
    <div style="background: linear-gradient(135deg, #1976D2 0%, #0D47A1 100%); padding: 20px; border-radius: 10px; text-align: center; color: white; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <h3 style="color: white; margin: 0; font-size: 36px;">📦</h3>
        <p style="font-size: 32px; font-weight: bold; margin: 10px 0;">{}</p>
        <p style="font-size: 14px; margin: 0;">Ürün</p>
    </div>
    
    <div style="background: linear-gradient(135deg, #00897B 0%, #004D40 100%); padding: 20px; border-radius: 10px; text-align: center; color: white; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <h3 style="color: white; margin: 0; font-size: 36px;">🛒</h3>
        <p style="font-size: 32px; font-weight: bold; margin: 10px 0;">{}</p>
        <p style="font-size: 14px; margin: 0;">Sipariş</p>
    </div>
    
    <div style="background: linear-gradient(135deg, #D84315 0%, #BF360C 100%); padding: 20px; border-radius: 10px; text-align: center; color: white; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <h3 style="color: white; margin: 0; font-size: 36px;">📝</h3>
        <p style="font-size: 32px; font-weight: bold; margin: 10px 0;">{}</p>
        <p style="font-size: 14px; margin: 0;">Sipariş Kalemi</p>
    </div>
    
</div>
"""

# Her tablodan kayıt sayısını çekiyoruz
customer_count = cursor.execute("SELECT COUNT(*) FROM customers").fetchone()[0]
product_count = cursor.execute("SELECT COUNT(*) FROM products").fetchone()[0]
order_count = cursor.execute("SELECT COUNT(*) FROM orders").fetchone()[0]
item_count = cursor.execute("SELECT COUNT(*) FROM order_items").fetchone()[0]

# HTML'i istatistiklerle doldur ve göster
display(HTML(stats_html.format(customer_count, product_count, order_count, item_count)))

print(f"\n✅ Veritabanı başarıyla oluşturuldu ve dolduruldu!")
print(f"📊 Toplam: {customer_count} müşteri, {product_count} ürün, {order_count} sipariş, {item_count} sipariş kalemi")

✅ Veritabanı başarıyla oluşturuldu ve dolduruldu!
📊 Toplam: 15 müşteri, 15 ürün, 18 sipariş, 18 sipariş kalemi

---

<div style="background-color: #E8EAF6; padding: 20px; border-radius: 10px; text-align: center; margin: 30px 0;">
    <h2 style="color: #3F51B5; margin-top: 0;">🎉 Adım 2 Tamamlandı!</h2>
    <p style="font-size: 16px; color: #5C6BC0;">
        Artık çalışmaya hazır bir e-ticaret veritabanımız var!<br/>
        Hadi bir sonraki adımda SQL sorguları yazmaya başlayalım! 🚀
    </p>
</div>

---
---

# 🔍 ADIM 3: SELECT - Veri Okuma Temelleri

<div style="background: linear-gradient(135deg, #00897B 0%, #004D40 100%); padding: 25px; border-radius: 15px; color: white; margin: 20px 0;">
    <h2 style="color: white; margin-top: 0;">🎯 Bu Adımda Neler Öğreneceğiz?</h2>
    <ul style="font-size: 16px; line-height: 1.8;">
        <li>✅ <strong>SELECT *</strong> ile tüm kolonları çekme</li>
        <li>✅ Belirli <strong>kolonları seçme</strong></li>
        <li>✅ <strong>LIMIT</strong> ile satır sayısını sınırlama</li>
        <li>✅ Pandas ile sonuçları <strong>güzel görüntüleme</strong></li>
        <li>✅ YBS senaryolarında pratik örnekler</li>
    </ul>
</div>

## 🎯 SELECT: SQL'in Kalbi

<div style="background-color: #FFF3E0; padding: 20px; border-left: 5px solid #F57C00; border-radius: 10px; margin: 20px 0;">
    <h3 style="color: #E65100; margin-top: 0;">💡 SELECT Nedir?</h3>
    <p style="font-size: 16px; line-height: 1.7;">
        <strong>SELECT</strong>, veritabanından veri <strong>okumak/çekmek</strong> için kullanılan en temel SQL komutudur. 
        Veri biliminde zamanınızın %80'ini SELECT sorguları yazarak geçireceksiniz!
    </p>
    <p style="font-size: 16px; line-height: 1.7; margin-bottom: 0;">
        <strong>Temel Sözdizimi:</strong>
    </p>
    <pre style="background: linear-gradient(135deg, #E3F2FD 0%, #BBDEFB 100%); color: #0D47A1; padding: 15px; border-radius: 8px; margin-top: 10px; border: 2px solid #90CAF9;">
<code style="font-weight: 600;">SELECT kolon_adları
FROM tablo_adı;</code>
    </pre>
</div>

```mermaid
graph LR
    A["📝 SQL Sorgusu<br/>SELECT * FROM customers"] --> B["🔄 Veritabanı<br/>Sorgu İşleme"]
    B --> C["📊 Sonuç Seti<br/>Tüm Müşteriler"]
    C --> D["🐍 Python<br/>DataFrame"]
    D --> E["👀 Görselleştirme<br/>Tablo"]
    
    style A fill:#FFD54F,stroke:#F57C00,stroke-width:2px
    style B fill:#90CAF9,stroke:#1976D2,stroke-width:2px
    style C fill:#A5D6A7,stroke:#388E3C,stroke-width:2px
    style D fill:#CE93D8,stroke:#7B1FA2,stroke-width:2px
    style E fill:#FFAB91,stroke:#D84315,stroke-width:2px
```

---

## 🌟 SELECT * : Tüm Kolonları Çekme

**Yıldız (*)** sembolü **"her şey"** demektir. Tablodaki **tüm kolonları** getirir.

### 📋 Örnek 1: Müşteri Tablosundaki Tüm Verileri Görüntüleme

In [15]:
# SQL sorgusu: Customers tablosundan TÜM kolonları ve TÜM satırları çek
query = """
SELECT * 
FROM customers
"""

# Sorguyu çalıştır ve pandas DataFrame'e çevir
df_customers = pd.read_sql_query(query, conn)

# Başlık
print("=" * 80)
print("👥 TÜM MÜŞTERİ VERİLERİ (SELECT * FROM customers)")
print("=" * 80)

# DataFrame'i göster
display(df_customers)

# İstatistikler
print(f"\n📊 Toplam {len(df_customers)} müşteri kaydı bulundu.")
print(f"📋 Kolonlar: {', '.join(df_customers.columns)}")

================================================================================
👥 TÜM MÜŞTERİ VERİLERİ (SELECT * FROM customers)
================================================================================

,customer_id,first_name,last_name,email,city,age,registration_date
0,1,Ahmet,Yılmaz,ahmet.yilmaz@gmail.com,İstanbul,28,2024-01-15
1,2,Ayşe,Demir,ayse.demir@hotmail.com,Ankara,35,2024-02-20
2,3,Mehmet,Kaya,mehmet.kaya@yahoo.com,İzmir,42,2024-01-10
3,4,Fatma,Şahin,fatma.sahin@gmail.com,İstanbul,31,2024-03-05
4,5,Ali,Çelik,ali.celik@outlook.com,Bursa,25,2024-02-14
5,6,Zeynep,Arslan,zeynep.arslan@gmail.com,Ankara,29,2024-01-20
6,7,Mustafa,Yıldız,mustafa.yildiz@gmail.com,Antalya,38,2024-03-12
7,8,Elif,Aydın,elif.aydin@hotmail.com,İzmir,26,2024-02-28
8,9,Hüseyin,Öztürk,huseyin.ozturk@gmail.com,İstanbul,45,2024-01-08
9,10,Merve,Polat,merve.polat@yahoo.com,Konya,33,2024-03-18
10,11,Emre,Kurt,emre.kurt@gmail.com,Ankara,27,2024-02-05
11,12,Selin,Şen,selin.sen@hotmail.com,İzmir,30,2024-01-25
12,13,Burak,Acar,burak.acar@gmail.com,İstanbul,36,2024-03-01
13,14,Deniz,Koç,deniz.koc@outlook.com,Bursa,24,2024-02-10
14,15,Cem,Özdemir,cem.ozdemir@gmail.com,Antalya,40,2024-01-30

📊 Toplam 15 müşteri kaydı bulundu.
📋 Kolonlar: customer_id, first_name, last_name, email, city, age, registration_date

<div style="background-color: #E8F5E9; padding: 20px; border-radius: 10px; margin: 20px 0;">
    <h3 style="color: #2E7D32; margin-top: 0;">💼 YBS Senaryosu</h3>
    <p style="font-size: 15px; line-height: 1.7;">
        <strong>Durum:</strong> Pazarlama ekibi size <em>"Sistemdeki tüm müşterilerin listesini çıkarabilir misin?"</em> diye soruyor.
    </p>
    <p style="font-size: 15px; line-height: 1.7; margin-bottom: 0;">
        <strong>Çözüm:</strong> <code>SELECT * FROM customers</code> ile tüm müşteri verilerini çekip Excel'e aktarabilirsiniz. 
        Ancak dikkat! Büyük tablolarda bu çok ağır olabilir. İşte bu yüzden <strong>LIMIT</strong> öğreneceğiz! 🎯
    </p>
</div>

---

## 🎚️ LIMIT: Satır Sayısını Sınırlama

**LIMIT**, sorgu sonucunda **maksimum kaç satır** getirileceğini belirtir. Büyük tablolarda **mutlaka** kullanılmalıdır!

### 📋 Örnek 2: İlk 5 Müşteriyi Görüntüleme

In [16]:
# SQL sorgusu: Sadece ilk 5 müşteriyi getir
query = """
SELECT * 
FROM customers
LIMIT 5
"""

# Sorguyu çalıştır
df_top5 = pd.read_sql_query(query, conn)

# Başlık
print("=" * 80)
print("👥 İLK 5 MÜŞTERİ (SELECT * FROM customers LIMIT 5)")
print("=" * 80)

# DataFrame'i göster
display(df_top5)

print(f"\n✅ LIMIT 5 sayesinde sadece {len(df_top5)} satır geldi!")
print("💡 İpucu: Büyük tablolarda 'hızlı bakış' için LIMIT kullanın!")

================================================================================
👥 İLK 5 MÜŞTERİ (SELECT * FROM customers LIMIT 5)
================================================================================

,customer_id,first_name,last_name,email,city,age,registration_date
0,1,Ahmet,Yılmaz,ahmet.yilmaz@gmail.com,İstanbul,28,2024-01-15
1,2,Ayşe,Demir,ayse.demir@hotmail.com,Ankara,35,2024-02-20
2,3,Mehmet,Kaya,mehmet.kaya@yahoo.com,İzmir,42,2024-01-10
3,4,Fatma,Şahin,fatma.sahin@gmail.com,İstanbul,31,2024-03-05
4,5,Ali,Çelik,ali.celik@outlook.com,Bursa,25,2024-02-14

✅ LIMIT 5 sayesinde sadece 5 satır geldi!
💡 İpucu: Büyük tablolarda 'hızlı bakış' için LIMIT kullanın!

### 📋 Örnek 3: Ürünler Tablosundan İlk 10 Kayıt

In [17]:
# Ürün kataloğuna hızlı bakış
query = """
SELECT *
FROM products
LIMIT 10
"""

df_products = pd.read_sql_query(query, conn)

print("=" * 80)
print("📦 ÜRÜN KATALOĞU - İLK 10 ÜRÜN")
print("=" * 80)
display(df_products)

print(f"\n💰 Fiyat aralığı: {df_products['price'].min():,.0f} ₺ - {df_products['price'].max():,.0f} ₺")
print(f"📊 Kategoriler: {', '.join(df_products['category'].unique())}")

================================================================================
📦 ÜRÜN KATALOĞU - İLK 10 ÜRÜN
================================================================================

   product_id                  name      category    price  stock
0           1         iPhone 15 Pro       Telefon  45999.0     50
1           2    Samsung Galaxy S24       Telefon  38999.0     45
2           3        MacBook Air M2        Laptop  52999.0     30
3           4           Dell XPS 15        Laptop  48999.0     25
4           5              iPad Air        Tablet  24999.0     60
5           6       Sony WH-1000XM5      Kulaklık  12999.0    100
6           7  Apple Watch Series 9          Saat  18999.0     40
7           8   Samsung Galaxy Buds      Kulaklık   3499.0    150
8           9        LG 55" OLED TV    Televizyon  35999.0     20
9          10         PlayStation 5  Oyun Konsolu  21999.0     35

💰 Fiyat aralığı: 3,499 ₺ - 52,999 ₺
📊 Kategoriler: Telefon, Laptop, Tablet, Kulaklık, Saat, Televizyon, Oyun Konsolu

---

## 📌 Belirli Kolonları Seçme

Çoğu zaman **tüm kolonlara** ihtiyacınız olmaz. Sadece **gerekli kolonları** seçerek hem **performans** kazanır hem de **okunabilirliği** artırırsınız.

### 📋 Örnek 4: Sadece İsim ve Email Çekme

In [18]:
# Sadece isim ve email kolonlarını seçiyoruz
query = """
SELECT first_name, last_name, email
FROM customers
LIMIT 10
"""

df_contact = pd.read_sql_query(query, conn)

print("=" * 80)
print("📧 MÜŞTERİ İLETİŞİM LİSTESİ (Sadece İsim ve Email)")
print("=" * 80)
display(df_contact)

print(f"\n✅ Sadece {len(df_contact.columns)} kolon çektik (customer_id, city, age gelmedi)")
print("💡 Gereksiz kolonları çekmemek, büyük tablolarda ciddi performans kazandırır!")

================================================================================
📧 MÜŞTERİ İLETİŞİM LİSTESİ (Sadece İsim ve Email)
================================================================================

  first_name last_name                     email
0      Ahmet    Yılmaz    ahmet.yilmaz@gmail.com
1       Ayşe     Demir    ayse.demir@hotmail.com
2     Mehmet      Kaya     mehmet.kaya@yahoo.com
3      Fatma     Şahin     fatma.sahin@gmail.com
4        Ali     Çelik     ali.celik@outlook.com
5     Zeynep    Arslan   zeynep.arslan@gmail.com
6    Mustafa    Yıldız  mustafa.yildiz@gmail.com
7       Elif     Aydın    elif.aydin@hotmail.com
8    Hüseyin    Öztürk  huseyin.ozturk@gmail.com
9      Merve     Polat     merve.polat@yahoo.com

✅ Sadece 3 kolon çektik (customer_id, city, age gelmedi)
💡 Gereksiz kolonları çekmemek, büyük tablolarda ciddi performans kazandırır!

### 📋 Örnek 5: Ürün İsmi ve Fiyatları

In [19]:
# Fiyat listesi oluşturma
query = """
SELECT name, price
FROM products
"""

df_price_list = pd.read_sql_query(query, conn)

print("=" * 80)
print("💰 FİYAT LİSTESİ (name, price)")
print("=" * 80)
display(df_price_list)

# En pahalı ve en ucuz ürün
en_pahali = df_price_list.loc[df_price_list['price'].idxmax()]
en_ucuz = df_price_list.loc[df_price_list['price'].idxmin()]

print(f"\n🔝 En pahalı: {en_pahali['name']} - {en_pahali['price']:,.0f} ₺")
print(f"💵 En ucuz: {en_ucuz['name']} - {en_ucuz['price']:,.0f} ₺")

================================================================================
💰 FİYAT LİSTESİ (name, price)
================================================================================

                    name    price
0          iPhone 15 Pro  45999.0
1     Samsung Galaxy S24  38999.0
2         MacBook Air M2  52999.0
3            Dell XPS 15  48999.0
4               iPad Air  24999.0
5        Sony WH-1000XM5  12999.0
6   Apple Watch Series 9  18999.0
7    Samsung Galaxy Buds   3499.0
8         LG 55" OLED TV  35999.0
9          PlayStation 5  21999.0
10       Nintendo Switch  11999.0
11          Canon EOS R6  89999.0
12         GoPro Hero 12  16999.0
13             Dyson V15  22999.0
14  Xiaomi Robot Süpürge   8999.0

🔝 En pahalı: Canon EOS R6 - 89,999 ₺
💵 En ucuz: Samsung Galaxy Buds - 3,499 ₺

### 📋 Örnek 6: Şehir ve Yaş Bilgileri

In [20]:
# Müşteri segmentasyonu için şehir ve yaş
query = """
SELECT first_name, city, age
FROM customers
"""

df_demographics = pd.read_sql_query(query, conn)

print("=" * 80)
print("🌍 MÜŞTERİ DEMOGRAFİK BİLGİLERİ")
print("=" * 80)
display(df_demographics.head(10))

# Şehir dağılımı
print("\n📊 Şehir Dağılımı:")
print(df_demographics['city'].value_counts().to_string())

print(f"\n📈 Ortalama Yaş: {df_demographics['age'].mean():.1f}")
print(f"👴 En yaşlı müşteri: {df_demographics['age'].max()} yaşında")
print(f"👶 En genç müşteri: {df_demographics['age'].min()} yaşında")

================================================================================
🌍 MÜŞTERİ DEMOGRAFİK BİLGİLERİ
================================================================================

  first_name      city  age
0      Ahmet  İstanbul   28
1       Ayşe    Ankara   35
2     Mehmet     İzmir   42
3      Fatma  İstanbul   31
4        Ali     Bursa   25
5     Zeynep    Ankara   29
6    Mustafa   Antalya   38
7       Elif     İzmir   26
8    Hüseyin  İstanbul   45
9      Merve     Konya   33

📊 Şehir Dağılımı:
city
İstanbul    4
Ankara      3
İzmir       3
Bursa       2
Antalya     2
Konya       1

📈 Ortalama Yaş: 32.6
👴 En yaşlı müşteri: 45 yaşında
👶 En genç müşteri: 24 yaşında

---

## 🎴 FLASHCARD: SELECT ve LIMIT Komutları

In [21]:
# SELECT ve LIMIT komutları için flashcard'lar
flashcards_select = """
<div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin: 20px 0;">
    
    <div style="background: linear-gradient(135deg, #5E35B1 0%, #4A148C 100%); padding: 20px; border-radius: 10px; color: white; min-height: 150px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <h4 style="color: white; margin-top: 0; font-size: 16px;">📊 SELECT *</h4>
        <p style="font-size: 14px; line-height: 1.6; margin-bottom: 0;">
            Tablodaki <strong>TÜM kolonları</strong> getirir.<br/>
            <code style="background: rgba(255,255,255,0.2); padding: 2px 6px; border-radius: 3px;">SELECT * FROM customers</code><br/>
            ⚠️ Büyük tablolarda dikkatli kullanın!
        </p>
    </div>
    
    <div style="background: linear-gradient(135deg, #1976D2 0%, #0D47A1 100%); padding: 20px; border-radius: 10px; color: white; min-height: 150px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <h4 style="color: white; margin-top: 0; font-size: 16px;">🎯 SELECT kolon_adı</h4>
        <p style="font-size: 14px; line-height: 1.6; margin-bottom: 0;">
            <strong>Belirli kolonları</strong> seçer.<br/>
            <code style="background: rgba(255,255,255,0.2); padding: 2px 6px; border-radius: 3px;">SELECT name, price FROM products</code><br/>
            ✅ Performans için en iyi yöntem!
        </p>
    </div>
    
    <div style="background: linear-gradient(135deg, #00897B 0%, #004D40 100%); padding: 20px; border-radius: 10px; color: white; min-height: 150px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <h4 style="color: white; margin-top: 0; font-size: 16px;">🎚️ LIMIT</h4>
        <p style="font-size: 14px; line-height: 1.6; margin-bottom: 0;">
            Maksimum <strong>satır sayısını</strong> belirler.<br/>
            <code style="background: rgba(255,255,255,0.2); padding: 2px 6px; border-radius: 3px;">SELECT * FROM orders LIMIT 10</code><br/>
            💡 Hızlı bakış için kullanın!
        </p>
    </div>
    
    <div style="background: linear-gradient(135deg, #D84315 0%, #BF360C 100%); padding: 20px; border-radius: 10px; color: white; min-height: 150px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <h4 style="color: white; margin-top: 0; font-size: 16px;">🔄 pd.read_sql_query()</h4>
        <p style="font-size: 14px; line-height: 1.6; margin-bottom: 0;">
            SQL sorgusunu çalıştırıp <strong>DataFrame'e çevirir</strong>.<br/>
            <code style="background: rgba(255,255,255,0.2); padding: 2px 6px; border-radius: 3px;">df = pd.read_sql_query(query, conn)</code><br/>
            🐍 Python-SQL köprüsü!
        </p>
    </div>
    
</div>
"""

display(HTML(flashcards_select))

---

## 💼 YBS Pratik Senaryoları

### 🎯 Senaryo 1: "Müşteri Listesi Çıkar"

<div style="background-color: #E3F2FD; padding: 15px; border-left: 4px solid #1976D2; margin: 15px 0;">
    <strong>📝 Talep:</strong> "Tüm müşterilerin isim, email ve şehir bilgilerini Excel'e aktarmam lazım."
</div>

In [22]:
# Çözüm: Sadece gerekli kolonları seç
query = """
SELECT first_name, last_name, email, city
FROM customers
"""

df_customer_list = pd.read_sql_query(query, conn)

print("✅ ÇÖZÜM: Müşteri Listesi Hazır!")
display(df_customer_list)

# Excel'e aktarma (isteğe bağlı)
# df_customer_list.to_excel('musteri_listesi.xlsx', index=False)
print(f"\n📊 Toplam {len(df_customer_list)} müşteri")
print("💾 DataFrame hazır, gerekirse Excel'e aktarabilirsiniz!")

✅ ÇÖZÜM: Müşteri Listesi Hazır!

   first_name last_name                     email      city
0       Ahmet    Yılmaz    ahmet.yilmaz@gmail.com  İstanbul
1        Ayşe     Demir    ayse.demir@hotmail.com    Ankara
2      Mehmet      Kaya     mehmet.kaya@yahoo.com     İzmir
3       Fatma     Şahin     fatma.sahin@gmail.com  İstanbul
4         Ali     Çelik     ali.celik@outlook.com     Bursa
5      Zeynep    Arslan   zeynep.arslan@gmail.com    Ankara
6     Mustafa    Yıldız  mustafa.yildiz@gmail.com   Antalya
7        Elif     Aydın    elif.aydin@hotmail.com     İzmir
8     Hüseyin    Öztürk  huseyin.ozturk@gmail.com  İstanbul
9       Merve     Polat     merve.polat@yahoo.com     Konya
10       Emre      Kurt       emre.kurt@gmail.com    Ankara
11      Selin       Şen     selin.sen@hotmail.com     İzmir
12      Burak      Acar      burak.acar@gmail.com  İstanbul
13      Deniz       Koç     deniz.koc@outlook.com     Bursa
14        Cem   Özdemir     cem.ozdemir@gmail.com   Antalya

📊 Toplam 15 müşteri
💾 DataFrame hazır, gerekirse Excel'e aktarabilirsiniz!

### 🎯 Senaryo 2: "Sisteme Yeni Bakmak İstiyorum"

<div style="background-color: #FFF3E0; padding: 15px; border-left: 4px solid #F57C00; margin: 15px 0;">
    <strong>📝 Talep:</strong> "Siparişler tablosuna hızlıca göz atmak istiyorum, nasıl bakmalıyım?"
</div>

In [23]:
# Çözüm: LIMIT ile hızlı bakış
query = """
SELECT *
FROM orders
LIMIT 5
"""

df_quick_look = pd.read_sql_query(query, conn)

print("✅ ÇÖZÜM: İlk 5 Sipariş (Hızlı Bakış)")
display(df_quick_look)

print(f"\n💡 İpucu: LIMIT sayesinde sistemi tanırken tüm veriyi çekmedik!")
print(f"📊 Kolonlar: {', '.join(df_quick_look.columns)}")
print(f"🎯 Artık tablonun yapısını biliyoruz!")

✅ ÇÖZÜM: İlk 5 Sipariş (Hızlı Bakış)

   order_id  customer_id  order_date         status  total_amount
0         1            1  2025-11-15  Teslim Edildi       45999.0
1         2            2  2025-11-20  Teslim Edildi       38999.0
2         3            3  2025-12-01  Teslim Edildi       52999.0
3         4            1  2025-12-10  Teslim Edildi       12999.0
4         5            4  2025-12-15        Kargoda       24999.0

💡 İpucu: LIMIT sayesinde sistemi tanırken tüm veriyi çekmedik!
📊 Kolonlar: order_id, customer_id, order_date, status, total_amount
🎯 Artık tablonun yapısını biliyoruz!

### 🎯 Senaryo 3: "Stok Takibi Yapacağım"

<div style="background-color: #E8F5E9; padding: 15px; border-left: 4px solid #388E3C; margin: 15px 0;">
    <strong>📝 Talep:</strong> "Ürün isimlerini ve stok miktarlarını görmem lazım."
</div>

In [24]:
# Çözüm: Sadece name ve stock kolonlarını çek
query = """
SELECT name, stock
FROM products
"""

df_stock = pd.read_sql_query(query, conn)

print("✅ ÇÖZÜM: Stok Durumu")
display(df_stock)

# Stok analizi
print(f"\n📦 Toplam ürün çeşidi: {len(df_stock)}")
print(f"📊 Toplam stok: {df_stock['stock'].sum()} adet")
print(f"⚠️ En düşük stok: {df_stock.loc[df_stock['stock'].idxmin(), 'name']} ({df_stock['stock'].min()} adet)")
print(f"✅ En yüksek stok: {df_stock.loc[df_stock['stock'].idxmax(), 'name']} ({df_stock['stock'].max()} adet)")

✅ ÇÖZÜM: Stok Durumu

                    name  stock
0          iPhone 15 Pro     50
1     Samsung Galaxy S24     45
2         MacBook Air M2     30
3            Dell XPS 15     25
4               iPad Air     60
5        Sony WH-1000XM5    100
6   Apple Watch Series 9     40
7    Samsung Galaxy Buds    150
8         LG 55" OLED TV     20
9          PlayStation 5     35
10       Nintendo Switch     55
11          Canon EOS R6     15
12         GoPro Hero 12     40
13             Dyson V15     25
14  Xiaomi Robot Süpürge     50

📦 Toplam ürün çeşidi: 15
📊 Toplam stok: 740 adet
⚠️ En düşük stok: Canon EOS R6 (15 adet)
✅ En yüksek stok: Samsung Galaxy Buds (150 adet)

---

<div style="background-color: #E8EAF6; padding: 20px; border-radius: 10px; text-align: center; margin: 30px 0;">
    <h2 style="color: #3F51B5; margin-top: 0;">🎉 Adım 3 Tamamlandı!</h2>
    <p style="font-size: 16px; color: #5C6BC0;">
        Artık SELECT komutunu kullanarak veri çekebiliyorsunuz!<br/>
        Bir sonraki adımda WHERE ile filtreleme öğrenerek süper güçlü sorgular yazacağız! 🚀
    </p>
</div>

---
---

# 🎯 ADIM 4: WHERE - Filtreleme ve Koşullar

<div style="background: linear-gradient(135deg, #7B1FA2 0%, #4A148C 100%); padding: 25px; border-radius: 15px; color: white; margin: 20px 0;">
    <h2 style="color: white; margin-top: 0;">🎯 Bu Adımda Neler Öğreneceğiz?</h2>
    <ul style="font-size: 16px; line-height: 1.8;">
        <li>✅ <strong>WHERE</strong> ile temel filtreleme</li>
        <li>✅ <strong>Karşılaştırma operatörleri</strong> (=, >, <, >=, <=, !=)</li>
        <li>✅ <strong>LIKE</strong> ile metin arama</li>
        <li>✅ <strong>IN</strong> ile çoklu değer filtreleme</li>
        <li>✅ <strong>BETWEEN</strong> ile aralık belirleme</li>
        <li>✅ YBS senaryolarında pratik örnekler</li>
    </ul>
</div>

## 🔍 WHERE: SQL'in Süper Gücü

<div style="background-color: #FFF9C4; padding: 20px; border-left: 5px solid #F57C00; border-radius: 10px; margin: 20px 0;">
    <h3 style="color: #E65100; margin-top: 0;">💡 WHERE Nedir?</h3>
    <p style="font-size: 16px; line-height: 1.7;">
        <strong>WHERE</strong>, SQL sorgularında <strong>koşul belirtmek</strong> için kullanılır. 
        "Sadece şu şartı sağlayan kayıtları getir" demenizi sağlar. Veri analizinde en çok kullanacağınız komutlardan biri!
    </p>
    <p style="font-size: 16px; line-height: 1.7; margin-bottom: 0;">
        <strong>Temel Sözdizimi:</strong>
    </p>
    <pre style="background: linear-gradient(135deg, #E3F2FD 0%, #BBDEFB 100%); color: #0D47A1; padding: 15px; border-radius: 8px; margin-top: 10px; border: 2px solid #90CAF9;">
<code style="font-weight: 600;">SELECT kolon_adları
FROM tablo_adı
WHERE koşul;</code>
    </pre>
</div>

```mermaid
graph TD
    A["📊 Tüm Veri<br/>15 Müşteri"] --> B{"🔍 WHERE Koşulu<br/>city = 'İstanbul'"}
    B -->|"✅ Koşul Sağlanıyor"| C["📋 Filtrelenmiş Veri<br/>4 İstanbul Müşterisi"]
    B -->|"❌ Koşul Sağlanmıyor"| D["🗑️ Elenen Veri<br/>11 Diğer Müşteri"]
    
    style A fill:#90CAF9,stroke:#1976D2,stroke-width:2px
    style B fill:#FFD54F,stroke:#F57C00,stroke-width:3px
    style C fill:#A5D6A7,stroke:#388E3C,stroke-width:2px
    style D fill:#FFAB91,stroke:#D84315,stroke-width:2px
```

---

## ⚖️ Karşılaştırma Operatörleri

WHERE koşullarında kullanabileceğiniz temel operatörler:

In [25]:
# Karşılaştırma operatörleri tablosu
operators_html = """
<div style="margin: 20px 0;">
    <table style="width: 100%; border-collapse: collapse; box-shadow: 0 2px 8px rgba(0,0,0,0.1);">
        <thead>
            <tr style="background: linear-gradient(135deg, #5E35B1 0%, #4A148C 100%); color: white;">
                <th style="padding: 15px; text-align: left; font-size: 16px;">Operatör</th>
                <th style="padding: 15px; text-align: left; font-size: 16px;">Anlamı</th>
                <th style="padding: 15px; text-align: left; font-size: 16px;">Örnek</th>
            </tr>
        </thead>
        <tbody>
            <tr style="background-color: #F3E5F5;">
                <td style="padding: 12px; font-weight: bold; color: #7B1FA2;">=</td>
                <td style="padding: 12px;">Eşittir</td>
                <td style="padding: 12px;"><code>city = 'İstanbul'</code></td>
            </tr>
            <tr style="background-color: #E1F5FE;">
                <td style="padding: 12px; font-weight: bold; color: #0277BD;">!=</td>
                <td style="padding: 12px;">Eşit değildir</td>
                <td style="padding: 12px;"><code>city != 'Ankara'</code></td>
            </tr>
            <tr style="background-color: #F3E5F5;">
                <td style="padding: 12px; font-weight: bold; color: #7B1FA2;">></td>
                <td style="padding: 12px;">Büyüktür</td>
                <td style="padding: 12px;"><code>age > 30</code></td>
            </tr>
            <tr style="background-color: #E1F5FE;">
                <td style="padding: 12px; font-weight: bold; color: #0277BD;"><</td>
                <td style="padding: 12px;">Küçüktür</td>
                <td style="padding: 12px;"><code>price < 10000</code></td>
            </tr>
            <tr style="background-color: #F3E5F5;">
                <td style="padding: 12px; font-weight: bold; color: #7B1FA2;">>=</td>
                <td style="padding: 12px;">Büyük eşittir</td>
                <td style="padding: 12px;"><code>age >= 18</code></td>
            </tr>
            <tr style="background-color: #E1F5FE;">
                <td style="padding: 12px; font-weight: bold; color: #0277BD;"><=</td>
                <td style="padding: 12px;">Küçük eşittir</td>
                <td style="padding: 12px;"><code>stock <= 50</code></td>
            </tr>
        </tbody>
    </table>
</div>
"""

display(HTML(operators_html))

---

## 📝 Eşitlik Filtreleme (=)

### 📋 Örnek 1: İstanbul'daki Müşteriler

In [26]:
# Sadece İstanbul'daki müşterileri getir
query = """
SELECT first_name, last_name, email, city, age
FROM customers
WHERE city = 'İstanbul'
"""

df_istanbul = pd.read_sql_query(query, conn)

print("=" * 80)
print("🏙️ İSTANBUL'DAKİ MÜŞTERİLER (WHERE city = 'İstanbul')")
print("=" * 80)
display(df_istanbul)

print(f"\n✅ Toplam {len(df_istanbul)} İstanbul müşterisi bulundu.")
print(f"📊 Ortalama yaş: {df_istanbul['age'].mean():.1f}")

================================================================================
🏙️ İSTANBUL'DAKİ MÜŞTERİLER (WHERE city = 'İstanbul')
================================================================================

  first_name last_name                     email      city  age
0      Ahmet    Yılmaz    ahmet.yilmaz@gmail.com  İstanbul   28
1      Fatma     Şahin     fatma.sahin@gmail.com  İstanbul   31
2    Hüseyin    Öztürk  huseyin.ozturk@gmail.com  İstanbul   45
3      Burak      Acar      burak.acar@gmail.com  İstanbul   36

✅ Toplam 4 İstanbul müşterisi bulundu.
📊 Ortalama yaş: 35.0

### 📋 Örnek 2: Telefon Kategorisindeki Ürünler

In [27]:
# Sadece telefon kategorisindeki ürünleri getir
query = """
SELECT name, category, price, stock
FROM products
WHERE category = 'Telefon'
"""

df_phones = pd.read_sql_query(query, conn)

print("=" * 80)
print("📱 TELEFON KATEGORİSİNDEKİ ÜRÜNLER (WHERE category = 'Telefon')")
print("=" * 80)
display(df_phones)

print(f"\n✅ {len(df_phones)} telefon modeli mevcut.")
print(f"💰 Ortalama fiyat: {df_phones['price'].mean():,.0f} ₺")
print(f"📦 Toplam stok: {df_phones['stock'].sum()} adet")

================================================================================
📱 TELEFON KATEGORİSİNDEKİ ÜRÜNLER (WHERE category = 'Telefon')
================================================================================

                 name category    price  stock
0       iPhone 15 Pro  Telefon  45999.0     50
1  Samsung Galaxy S24  Telefon  38999.0     45

✅ 2 telefon modeli mevcut.
💰 Ortalama fiyat: 42,499 ₺
📦 Toplam stok: 95 adet

---

## 🔢 Sayısal Karşılaştırmalar (>, <, >=, <=)

### 📋 Örnek 3: 30 Yaş Üstü Müşteriler

In [28]:
# 30 yaş üstü müşterileri getir
query = """
SELECT first_name, last_name, age, city
FROM customers
WHERE age > 30
"""

df_over_30 = pd.read_sql_query(query, conn)

print("=" * 80)
print("👴 30 YAŞ ÜSTÜ MÜŞTERİLER (WHERE age > 30)")
print("=" * 80)
display(df_over_30)

print(f"\n✅ {len(df_over_30)} müşteri 30 yaşın üstünde.")
print(f"📊 Yaş aralığı: {df_over_30['age'].min()} - {df_over_30['age'].max()}")
print(f"📍 Şehir dağılımı:")
print(df_over_30['city'].value_counts().to_string())

================================================================================
👴 30 YAŞ ÜSTÜ MÜŞTERİLER (WHERE age > 30)
================================================================================

  first_name last_name  age      city
0       Ayşe     Demir   35    Ankara
1     Mehmet      Kaya   42     İzmir
2      Fatma     Şahin   31  İstanbul
3    Mustafa    Yıldız   38   Antalya
4    Hüseyin    Öztürk   45  İstanbul
5      Merve     Polat   33     Konya
6      Burak      Acar   36  İstanbul
7        Cem   Özdemir   40   Antalya

✅ 8 müşteri 30 yaşın üstünde.
📊 Yaş aralığı: 31 - 45
📍 Şehir dağılımı:
city
İstanbul    3
Antalya     2
Ankara      1
İzmir       1
Konya       1

### 📋 Örnek 4: 20.000 TL Üzeri Ürünler

In [29]:
# Yüksek fiyatlı ürünler (20.000 TL ve üzeri)
query = """
SELECT name, category, price, stock
FROM products
WHERE price >= 20000
"""

df_premium = pd.read_sql_query(query, conn)

print("=" * 80)
print("💎 PREMİUM ÜRÜNLER - 20.000 TL ÜZERİ (WHERE price >= 20000)")
print("=" * 80)
display(df_premium)

print(f"\n✅ {len(df_premium)} premium ürün bulundu.")
print(f"💰 Ortalama fiyat: {df_premium['price'].mean():,.0f} ₺")
print(f"🏆 En pahalı: {df_premium.loc[df_premium['price'].idxmax(), 'name']} - {df_premium['price'].max():,.0f} ₺")

================================================================================
💎 PREMİUM ÜRÜNLER - 20.000 TL ÜZERİ (WHERE price >= 20000)
================================================================================

                 name            category    price  stock
0       iPhone 15 Pro             Telefon  45999.0     50
1  Samsung Galaxy S24             Telefon  38999.0     45
2      MacBook Air M2              Laptop  52999.0     30
3         Dell XPS 15              Laptop  48999.0     25
4            iPad Air              Tablet  24999.0     60
5      LG 55" OLED TV          Televizyon  35999.0     20
6       PlayStation 5        Oyun Konsolu  21999.0     35
7        Canon EOS R6   Fotoğraf Makinesi  89999.0     15
8           Dyson V15  Elektrikli Süpürge  22999.0     25

✅ 9 premium ürün bulundu.
💰 Ortalama fiyat: 42,555 ₺
🏆 En pahalı: Canon EOS R6 - 89,999 ₺

### 📋 Örnek 5: Düşük Stoklu Ürünler

In [30]:
# Stoku 30'un altında olan ürünler (acil sipariş gerekebilir)
query = """
SELECT name, category, stock, price
FROM products
WHERE stock < 30
"""

df_low_stock = pd.read_sql_query(query, conn)

print("=" * 80)
print("⚠️ DÜŞÜK STOKLU ÜRÜNLER (WHERE stock < 30)")
print("=" * 80)
display(df_low_stock)

print(f"\n⚠️ {len(df_low_stock)} üründe düşük stok durumu var!")
print(f"📦 En düşük stok: {df_low_stock['stock'].min()} adet ({df_low_stock.loc[df_low_stock['stock'].idxmin(), 'name']})")
print(f"💡 İpucu: Bu ürünler için tedarikçi ile iletişime geçilmeli!")

================================================================================
⚠️ DÜŞÜK STOKLU ÜRÜNLER (WHERE stock < 30)
================================================================================

             name            category  stock    price
0     Dell XPS 15              Laptop     25  48999.0
1  LG 55" OLED TV          Televizyon     20  35999.0
2    Canon EOS R6   Fotoğraf Makinesi     15  89999.0
3       Dyson V15  Elektrikli Süpürge     25  22999.0

⚠️ 4 üründe düşük stok durumu var!
📦 En düşük stok: 15 adet (Canon EOS R6)
💡 İpucu: Bu ürünler için tedarikçi ile iletişime geçilmeli!

---

## 🔤 LIKE: Metin Arama ve Pattern Matching

**LIKE** operatörü, metin kolonlarında **kısmi eşleşme** yapmak için kullanılır.

<div style="background-color: #E8F5E9; padding: 20px; border-radius: 10px; margin: 20px 0;">
    <h4 style="color: #2E7D32; margin-top: 0;">🎯 Wildcard (Joker) Karakterler</h4>
    <ul style="font-size: 15px; line-height: 1.7;">
        <li><strong>%</strong> → Herhangi bir karakter dizisi (0 veya daha fazla)</li>
        <li><strong>_</strong> → Tek bir karakter</li>
    </ul>
    <p style="font-size: 15px; margin: 10px 0;"><strong>Örnekler:</strong></p>
    <ul style="font-size: 14px; line-height: 1.7;">
        <li><code>'A%'</code> → A ile başlayan (Ahmet, Ali, Ayşe)</li>
        <li><code>'%gmail%'</code> → gmail içeren (ahmet@gmail.com)</li>
        <li><code>'%son'</code> → son ile biten (terson, wilson)</li>
        <li><code>'M_rat'</code> → M ile başlayıp rat ile biten 5 harfli (Murat)</li>
    </ul>
</div>

### 📋 Örnek 6: İsmi 'A' ile Başlayan Müşteriler

In [31]:
# İsmi A harfi ile başlayan müşteriler
query = """
SELECT first_name, last_name, email, city
FROM customers
WHERE first_name LIKE 'A%'
"""

df_starts_a = pd.read_sql_query(query, conn)

print("=" * 80)
print("🅰️ İSMİ 'A' İLE BAŞLAYAN MÜŞTERİLER (WHERE first_name LIKE 'A%')")
print("=" * 80)
display(df_starts_a)

print(f"\n✅ {len(df_starts_a)} müşteri bulundu.")
print(f"📝 İsimler: {', '.join(df_starts_a['first_name'].unique())}")

================================================================================
🅰️ İSMİ 'A' İLE BAŞLAYAN MÜŞTERİLER (WHERE first_name LIKE 'A%')
================================================================================

  first_name last_name                   email      city
0      Ahmet    Yılmaz  ahmet.yilmaz@gmail.com  İstanbul
1       Ayşe     Demir  ayse.demir@hotmail.com    Ankara
2        Ali     Çelik   ali.celik@outlook.com     Bursa

✅ 3 müşteri bulundu.
📝 İsimler: Ahmet, Ayşe, Ali

### 📋 Örnek 7: Gmail Kullanan Müşteriler

In [32]:
# Email adresi gmail olan müşteriler
query = """
SELECT first_name, last_name, email
FROM customers
WHERE email LIKE '%gmail%'
"""

df_gmail = pd.read_sql_query(query, conn)

print("=" * 80)
print("📧 GMAIL KULLANAN MÜŞTERİLER (WHERE email LIKE '%gmail%')")
print("=" * 80)
display(df_gmail)

print(f"\n✅ {len(df_gmail)} müşteri Gmail kullanıyor.")
print(f"📊 Toplam müşterinin %{(len(df_gmail)/15)*100:.1f}'ü Gmail tercih ediyor.")

================================================================================
📧 GMAIL KULLANAN MÜŞTERİLER (WHERE email LIKE '%gmail%')
================================================================================

  first_name last_name                     email
0      Ahmet    Yılmaz    ahmet.yilmaz@gmail.com
1      Fatma     Şahin     fatma.sahin@gmail.com
2     Zeynep    Arslan   zeynep.arslan@gmail.com
3    Mustafa    Yıldız  mustafa.yildiz@gmail.com
4    Hüseyin    Öztürk  huseyin.ozturk@gmail.com
5       Emre      Kurt       emre.kurt@gmail.com
6      Burak      Acar      burak.acar@gmail.com
7        Cem   Özdemir     cem.ozdemir@gmail.com

✅ 8 müşteri Gmail kullanıyor.
📊 Toplam müşterinin %53.3'ü Gmail tercih ediyor.

### 📋 Örnek 8: İsminde 'Phone' Geçen Ürünler

In [33]:
# Ürün isminde 'Phone' geçenler (iPhone, Galaxy Phone vs.)
query = """
SELECT name, category, price, stock
FROM products
WHERE name LIKE '%Phone%'
"""

df_phones_like = pd.read_sql_query(query, conn)

print("=" * 80)
print("📱 İSMİNDE 'PHONE' GEÇEN ÜRÜNLER (WHERE name LIKE '%Phone%')")
print("=" * 80)
display(df_phones_like)

if len(df_phones_like) > 0:
    print(f"\n✅ {len(df_phones_like)} ürün bulundu.")
else:
    print("\n⚠️ İsminde 'Phone' geçen ürün bulunamadı.")
    print("💡 İpucu: LIKE büyük-küçük harf duyarlıdır (case-sensitive)!")

================================================================================
📱 İSMİNDE 'PHONE' GEÇEN ÜRÜNLER (WHERE name LIKE '%Phone%')
================================================================================

            name category    price  stock
0  iPhone 15 Pro  Telefon  45999.0     50

✅ 1 ürün bulundu.

---

## 📦 IN: Çoklu Değer Filtreleme

**IN** operatörü, bir kolonun **birden fazla değerden birine eşit olup olmadığını** kontrol eder.

<div style="background-color: #FFF3E0; padding: 20px; border-radius: 10px; margin: 20px 0;">
    <h4 style="color: #E65100; margin-top: 0;">💡 IN Kullanımı</h4>
    <p style="font-size: 15px; line-height: 1.7; margin-bottom: 0;">
        <strong>Uzun yol:</strong> <code>WHERE city = 'İstanbul' OR city = 'Ankara' OR city = 'İzmir'</code><br/>
        <strong>Kısa yol:</strong> <code>WHERE city IN ('İstanbul', 'Ankara', 'İzmir')</code>
    </p>
</div>

### 📋 Örnek 9: Büyük Şehirlerdeki Müşteriler

In [34]:
# İstanbul, Ankara veya İzmir'deki müşteriler
query = """
SELECT first_name, last_name, city, age
FROM customers
WHERE city IN ('İstanbul', 'Ankara', 'İzmir')
"""

df_big_cities = pd.read_sql_query(query, conn)

print("=" * 80)
print("🏙️ BÜYÜK ŞEHİRLERDEKİ MÜŞTERİLER (WHERE city IN (...))")
print("=" * 80)
display(df_big_cities)

print(f"\n✅ {len(df_big_cities)} müşteri İstanbul, Ankara veya İzmir'de.")
print(f"📊 Şehir dağılımı:")
print(df_big_cities['city'].value_counts().to_string())

================================================================================
🏙️ BÜYÜK ŞEHİRLERDEKİ MÜŞTERİLER (WHERE city IN (...))
================================================================================

  first_name last_name      city  age
0      Ahmet    Yılmaz  İstanbul   28
1       Ayşe     Demir    Ankara   35
2     Mehmet      Kaya     İzmir   42
3      Fatma     Şahin  İstanbul   31
4     Zeynep    Arslan    Ankara   29
5       Elif     Aydın     İzmir   26
6    Hüseyin    Öztürk  İstanbul   45
7       Emre      Kurt    Ankara   27
8      Selin       Şen     İzmir   30
9      Burak      Acar  İstanbul   36

✅ 10 müşteri İstanbul, Ankara veya İzmir'de.
📊 Şehir dağılımı:
city
İstanbul    4
Ankara      3
İzmir       3

### 📋 Örnek 10: Belirli Kategorilerdeki Ürünler

In [35]:
# Telefon, Laptop veya Tablet kategorilerindeki ürünler
query = """
SELECT name, category, price, stock
FROM products
WHERE category IN ('Telefon', 'Laptop', 'Tablet')
"""

df_tech_categories = pd.read_sql_query(query, conn)

print("=" * 80)
print("💻 TEKNOLOJİ ÜRÜNLERİ (Telefon, Laptop, Tablet)")
print("=" * 80)
display(df_tech_categories)

print(f"\n✅ {len(df_tech_categories)} teknoloji ürünü bulundu.")
print(f"📊 Kategori dağılımı:")
print(df_tech_categories['category'].value_counts().to_string())
print(f"💰 Ortalama fiyat: {df_tech_categories['price'].mean():,.0f} ₺")

================================================================================
💻 TEKNOLOJİ ÜRÜNLERİ (Telefon, Laptop, Tablet)
================================================================================

                 name category    price  stock
0       iPhone 15 Pro  Telefon  45999.0     50
1  Samsung Galaxy S24  Telefon  38999.0     45
2      MacBook Air M2   Laptop  52999.0     30
3         Dell XPS 15   Laptop  48999.0     25
4            iPad Air   Tablet  24999.0     60

✅ 5 teknoloji ürünü bulundu.
📊 Kategori dağılımı:
category
Telefon    2
Laptop     2
Tablet     1
💰 Ortalama fiyat: 42,399 ₺

---

## 📏 BETWEEN: Aralık Belirleme

**BETWEEN** operatörü, bir değerin **belirli bir aralıkta olup olmadığını** kontrol eder (başlangıç ve bitiş değerleri **dahil**).

<div style="background-color: #E8EAF6; padding: 20px; border-radius: 10px; margin: 20px 0;">
    <h4 style="color: #3F51B5; margin-top: 0;">💡 BETWEEN Kullanımı</h4>
    <p style="font-size: 15px; line-height: 1.7; margin-bottom: 0;">
        <strong>Uzun yol:</strong> <code>WHERE age >= 25 AND age <= 35</code><br/>
        <strong>Kısa yol:</strong> <code>WHERE age BETWEEN 25 AND 35</code>
    </p>
</div>

### 📋 Örnek 11: 25-35 Yaş Aralığındaki Müşteriler

In [36]:
# 25-35 yaş arası müşteriler (genç yetişkin segment)
query = """
SELECT first_name, last_name, age, city
FROM customers
WHERE age BETWEEN 25 AND 35
"""

df_age_range = pd.read_sql_query(query, conn)

print("=" * 80)
print("👥 25-35 YAŞ ARASI MÜŞTERİLER (WHERE age BETWEEN 25 AND 35)")
print("=" * 80)
display(df_age_range)

print(f"\n✅ {len(df_age_range)} müşteri bu yaş aralığında.")
print(f"📊 Ortalama yaş: {df_age_range['age'].mean():.1f}")
print(f"🎯 Hedef segment: Genç yetişkinler")

================================================================================
👥 25-35 YAŞ ARASI MÜŞTERİLER (WHERE age BETWEEN 25 AND 35)
================================================================================

  first_name last_name  age      city
0      Ahmet    Yılmaz   28  İstanbul
1       Ayşe     Demir   35    Ankara
2      Fatma     Şahin   31  İstanbul
3        Ali     Çelik   25     Bursa
4     Zeynep    Arslan   29    Ankara
5       Elif     Aydın   26     İzmir
6      Merve     Polat   33     Konya
7       Emre      Kurt   27    Ankara
8      Selin       Şen   30     İzmir

✅ 9 müşteri bu yaş aralığında.
📊 Ortalama yaş: 29.3
🎯 Hedef segment: Genç yetişkinler

### 📋 Örnek 12: Orta Segment Fiyat Aralığı (10.000-30.000 TL)

In [37]:
# 10.000 - 30.000 TL arası ürünler (orta segment)
query = """
SELECT name, category, price, stock
FROM products
WHERE price BETWEEN 10000 AND 30000
"""

df_mid_range = pd.read_sql_query(query, conn)

print("=" * 80)
print("💰 ORTA SEGMENT ÜRÜNLER (10.000-30.000 TL)")
print("=" * 80)
display(df_mid_range)

print(f"\n✅ {len(df_mid_range)} orta segment ürün mevcut.")
print(f"💵 Ortalama fiyat: {df_mid_range['price'].mean():,.0f} ₺")
print(f"📦 Toplam stok değeri: {(df_mid_range['price'] * df_mid_range['stock']).sum():,.0f} ₺")

================================================================================
💰 ORTA SEGMENT ÜRÜNLER (10.000-30.000 TL)
================================================================================

                   name            category    price  stock
0              iPad Air              Tablet  24999.0     60
1       Sony WH-1000XM5            Kulaklık  12999.0    100
2  Apple Watch Series 9                Saat  18999.0     40
3         PlayStation 5        Oyun Konsolu  21999.0     35
4       Nintendo Switch        Oyun Konsolu  11999.0     55
5         GoPro Hero 12      Aksiyon Kamera  16999.0     40
6             Dyson V15  Elektrikli Süpürge  22999.0     25

✅ 7 orta segment ürün mevcut.
💵 Ortalama fiyat: 18,713 ₺
📦 Toplam stok değeri: 6,244,645 ₺

---

<div style="background-color: #E8EAF6; padding: 20px; border-radius: 10px; text-align: center; margin: 30px 0;">
    <h2 style="color: #3F51B5; margin-top: 0;">🎉 Adım 4 Tamamlandı!</h2>
    <p style="font-size: 16px; color: #5C6BC0;">
        Artık WHERE ile verileri filtreleyebiliyorsunuz!<br/>
        Bir sonraki adımda mantıksal operatörlerle çok daha güçlü sorgular yazacağız! 🔥
    </p>
</div>

---
---

# 🚀 ADIM 5: İleri Seviye Filtreleme ve Sıralama

<div style="background: linear-gradient(135deg, #1976D2 0%, #0D47A1 100%); padding: 25px; border-radius: 15px; color: white; margin: 20px 0;">
    <h2 style="color: white; margin-top: 0;">🎯 Bu Adımda Neler Öğreneceğiz?</h2>
    <ul style="font-size: 16px; line-height: 1.8;">
        <li>✅ <strong>AND</strong> - Birden fazla koşulu birleştirme</li>
        <li>✅ <strong>OR</strong> - Alternatif koşullar oluşturma</li>
        <li>✅ <strong>NOT</strong> - Koşulu tersine çevirme</li>
        <li>✅ <strong>ORDER BY</strong> - Sonuçları sıralama (ASC/DESC)</li>
        <li>✅ <strong>DISTINCT</strong> - Tekrarlanan kayıtları eleme</li>
        <li>✅ Karmaşık sorgu kombinasyonları</li>
    </ul>
</div>

## 🔗 AND: Birden Fazla Koşulu Birleştirme

**AND** operatörü, **TÜM koşulların aynı anda sağlanmasını** gerektirir.

<div style="background-color: #E8F5E9; padding: 20px; border-left: 5px solid #43A047; border-radius: 10px; margin: 20px 0;">
    <h3 style="color: #2E7D32; margin-top: 0;">💡 AND Mantığı</h3>
    <p style="font-size: 16px; line-height: 1.7;">
        <strong>Koşul1 AND Koşul2</strong> → Her iki koşul da <strong>TRUE</strong> olmalı!
    </p>
    <table style="width: 100%; margin-top: 15px; border-collapse: collapse;">
        <tr style="background-color: #C8E6C9;">
            <th style="padding: 10px; border: 1px solid #81C784;">Koşul 1</th>
            <th style="padding: 10px; border: 1px solid #81C784;">Koşul 2</th>
            <th style="padding: 10px; border: 1px solid #81C784;">Sonuç</th>
        </tr>
        <tr>
            <td style="padding: 8px; border: 1px solid #81C784;">✅ TRUE</td>
            <td style="padding: 8px; border: 1px solid #81C784;">✅ TRUE</td>
            <td style="padding: 8px; border: 1px solid #81C784; background-color: #A5D6A7;"><strong>✅ TRUE</strong></td>
        </tr>
        <tr>
            <td style="padding: 8px; border: 1px solid #81C784;">✅ TRUE</td>
            <td style="padding: 8px; border: 1px solid #81C784;">❌ FALSE</td>
            <td style="padding: 8px; border: 1px solid #81C784; background-color: #FFAB91;"><strong>❌ FALSE</strong></td>
        </tr>
        <tr>
            <td style="padding: 8px; border: 1px solid #81C784;">❌ FALSE</td>
            <td style="padding: 8px; border: 1px solid #81C784;">✅ TRUE</td>
            <td style="padding: 8px; border: 1px solid #81C784; background-color: #FFAB91;"><strong>❌ FALSE</strong></td>
        </tr>
        <tr>
            <td style="padding: 8px; border: 1px solid #81C784;">❌ FALSE</td>
            <td style="padding: 8px; border: 1px solid #81C784;">❌ FALSE</td>
            <td style="padding: 8px; border: 1px solid #81C784; background-color: #FFAB91;"><strong>❌ FALSE</strong></td>
        </tr>
    </table>
</div>

### 📋 Örnek 1: İstanbul'da Yaşayan 30 Yaş Üstü Müşteriler

In [38]:
# İstanbul'da ve 30 yaş üstü (İKİ KOŞUL DA SAĞLANMALI!)
query = """
SELECT first_name, last_name, age, city, email
FROM customers
WHERE city = 'İstanbul' AND age > 30
"""

df_istanbul_older = pd.read_sql_query(query, conn)

print("=" * 80)
print("🎯 İSTANBUL'DA YAŞAYAN 30 YAŞ ÜSTÜ MÜŞTERİLER")
print("=" * 80)
display(df_istanbul_older)

print(f"\n✅ {len(df_istanbul_older)} müşteri her iki koşulu da sağlıyor.")
print(f"📊 Ortalama yaş: {df_istanbul_older['age'].mean():.1f}")
print(f"💼 Hedef segment: İstanbul'daki deneyimli müşteriler")

================================================================================
🎯 İSTANBUL'DA YAŞAYAN 30 YAŞ ÜSTÜ MÜŞTERİLER
================================================================================

  first_name last_name  age      city                     email
0      Fatma     Şahin   31  İstanbul     fatma.sahin@gmail.com
1    Hüseyin    Öztürk   45  İstanbul  huseyin.ozturk@gmail.com
2      Burak      Acar   36  İstanbul      burak.acar@gmail.com

✅ 3 müşteri her iki koşulu da sağlıyor.
📊 Ortalama yaş: 37.3
💼 Hedef segment: İstanbul'daki deneyimli müşteriler

### 📋 Örnek 2: Premium Laptop'lar (20.000 TL Üzeri ve Stokta Var)

In [39]:
# Laptop kategorisi + 20.000 TL üzeri + Stokta mevcut
query = """
SELECT name, category, price, stock
FROM products
WHERE category = 'Laptop' AND price >= 20000 AND stock > 0
"""

df_premium_laptops = pd.read_sql_query(query, conn)

print("=" * 80)
print("💎 PREMİUM LAPTOP'LAR (20.000+ TL, Stokta Mevcut)")
print("=" * 80)
display(df_premium_laptops)

if len(df_premium_laptops) > 0:
    print(f"\n✅ {len(df_premium_laptops)} premium laptop stokta!")
    print(f"💰 Ortalama fiyat: {df_premium_laptops['price'].mean():,.0f} ₺")
    print(f"📦 Toplam stok değeri: {(df_premium_laptops['price'] * df_premium_laptops['stock']).sum():,.0f} ₺")
else:
    print("\n⚠️ Kriterlere uyan laptop bulunamadı!")

================================================================================
💎 PREMİUM LAPTOP'LAR (20.000+ TL, Stokta Mevcut)
================================================================================

             name category    price  stock
0  MacBook Air M2   Laptop  52999.0     30
1     Dell XPS 15   Laptop  48999.0     25

✅ 2 premium laptop stokta!
💰 Ortalama fiyat: 50,999 ₺
📦 Toplam stok değeri: 2,814,945 ₺

---

## 🔀 OR: Alternatif Koşullar

**OR** operatörü, **EN AZ BİR koşulun sağlanmasını** yeterli görür.

<div style="background-color: #FFF3E0; padding: 20px; border-left: 5px solid #F57C00; border-radius: 10px; margin: 20px 0;">
    <h3 style="color: #E65100; margin-top: 0;">💡 OR Mantığı</h3>
    <p style="font-size: 16px; line-height: 1.7;">
        <strong>Koşul1 OR Koşul2</strong> → En az biri <strong>TRUE</strong> olmalı!
    </p>
    <table style="width: 100%; margin-top: 15px; border-collapse: collapse;">
        <tr style="background-color: #FFE0B2;">
            <th style="padding: 10px; border: 1px solid #FFAB91;">Koşul 1</th>
            <th style="padding: 10px; border: 1px solid #FFAB91;">Koşul 2</th>
            <th style="padding: 10px; border: 1px solid #FFAB91;">Sonuç</th>
        </tr>
        <tr>
            <td style="padding: 8px; border: 1px solid #FFAB91;">✅ TRUE</td>
            <td style="padding: 8px; border: 1px solid #FFAB91;">✅ TRUE</td>
            <td style="padding: 8px; border: 1px solid #FFAB91; background-color: #A5D6A7;"><strong>✅ TRUE</strong></td>
        </tr>
        <tr>
            <td style="padding: 8px; border: 1px solid #FFAB91;">✅ TRUE</td>
            <td style="padding: 8px; border: 1px solid #FFAB91;">❌ FALSE</td>
            <td style="padding: 8px; border: 1px solid #FFAB91; background-color: #A5D6A7;"><strong>✅ TRUE</strong></td>
        </tr>
        <tr>
            <td style="padding: 8px; border: 1px solid #FFAB91;">❌ FALSE</td>
            <td style="padding: 8px; border: 1px solid #FFAB91;">✅ TRUE</td>
            <td style="padding: 8px; border: 1px solid #FFAB91; background-color: #A5D6A7;"><strong>✅ TRUE</strong></td>
        </tr>
        <tr>
            <td style="padding: 8px; border: 1px solid #FFAB91;">❌ FALSE</td>
            <td style="padding: 8px; border: 1px solid #FFAB91;">❌ FALSE</td>
            <td style="padding: 8px; border: 1px solid #FFAB91; background-color: #FFAB91;"><strong>❌ FALSE</strong></td>
        </tr>
    </table>
</div>

### 📋 Örnek 3: Genç veya Yaşlı Müşteriler (25 Altı veya 40 Üstü)

In [41]:
# 25 yaş altı VEYA 40 yaş üstü müşteriler
query = """
SELECT first_name, last_name, age, city
FROM customers
WHERE age < 25 OR age > 40
"""

df_age_extremes = pd.read_sql_query(query, conn)

print("=" * 80)
print("👶👴 GENÇ VEYA YAŞLI MÜŞTERİLER (age < 25 OR age > 40)")
print("=" * 80)
display(df_age_extremes)

print(f"\n✅ {len(df_age_extremes)} müşteri bu kriterleri sağlıyor.")
print(f"📊 Yaş dağılımı:")
young = df_age_extremes[df_age_extremes['age'] < 25]
old = df_age_extremes[df_age_extremes['age'] > 40]
print(f"   - 25 yaş altı: {len(young)} kişi")
print(f"   - 40 yaş üstü: {len(old)} kişi")

================================================================================
👶👴 GENÇ VEYA YAŞLI MÜŞTERİLER (age < 25 OR age > 40)
================================================================================

  first_name last_name  age      city
0     Mehmet      Kaya   42     İzmir
1    Hüseyin    Öztürk   45  İstanbul
2      Deniz       Koç   24     Bursa

✅ 3 müşteri bu kriterleri sağlıyor.
📊 Yaş dağılımı:
   - 25 yaş altı: 1 kişi
   - 40 yaş üstü: 2 kişi

### 📋 Örnek 4: Uygun Fiyatlı veya İndirimli Ürünler

In [42]:
# 5000 TL altı VEYA stoku 20'nin altında olan ürünler (indirim adayı)
query = """
SELECT name, category, price, stock
FROM products
WHERE price < 5000 OR stock < 20
"""

df_budget_or_low_stock = pd.read_sql_query(query, conn)

print("=" * 80)
print("💰 UYGUN FİYATLI VEYA DÜŞÜK STOKLU ÜRÜNLER")
print("=" * 80)
display(df_budget_or_low_stock)

print(f"\n✅ {len(df_budget_or_low_stock)} ürün listelendi.")
budget = df_budget_or_low_stock[df_budget_or_low_stock['price'] < 5000]
low_stock = df_budget_or_low_stock[df_budget_or_low_stock['stock'] < 20]
print(f"📊 Dağılım:")
print(f"   - 5000 TL altı: {len(budget)} ürün")
print(f"   - Düşük stok (<20): {len(low_stock)} ürün")

================================================================================
💰 UYGUN FİYATLI VEYA DÜŞÜK STOKLU ÜRÜNLER
================================================================================

                  name           category    price  stock
0  Samsung Galaxy Buds           Kulaklık   3499.0    150
1         Canon EOS R6  Fotoğraf Makinesi  89999.0     15

✅ 2 ürün listelendi.
📊 Dağılım:
   - 5000 TL altı: 1 ürün
   - Düşük stok (<20): 1 ürün

---

## 🚫 NOT: Koşulu Tersine Çevirme

**NOT** operatörü, bir koşulun **tam tersini** almak için kullanılır.

<div style="background-color: #FCE4EC; padding: 20px; border-left: 5px solid #C2185B; border-radius: 10px; margin: 20px 0;">
    <h3 style="color: #880E4F; margin-top: 0;">💡 NOT Kullanımı</h3>
    <p style="font-size: 16px; line-height: 1.7; margin-bottom: 10px;">
        <strong>NOT koşul</strong> → Koşulu tersine çevirir
    </p>
    <p style="font-size: 15px; line-height: 1.7; margin-bottom: 0;">
        <strong>Örnekler:</strong><br/>
        • <code>WHERE NOT city = 'İstanbul'</code> → İstanbul dışındaki şehirler<br/>
        • <code>WHERE city != 'İstanbul'</code> → Aynı sonuç (alternatif yazım)<br/>
        • <code>WHERE NOT age < 18</code> → 18 yaş ve üzeri
    </p>
</div>

### 📋 Örnek 5: İstanbul Dışındaki Müşteriler

In [43]:
# İstanbul dışındaki şehirlerden müşteriler
query = """
SELECT first_name, last_name, city, age
FROM customers
WHERE NOT city = 'İstanbul'
"""

df_not_istanbul = pd.read_sql_query(query, conn)

print("=" * 80)
print("🌍 İSTANBUL DIŞINDAKİ MÜŞTERİLER (WHERE NOT city = 'İstanbul')")
print("=" * 80)
display(df_not_istanbul)

print(f"\n✅ {len(df_not_istanbul)} müşteri İstanbul dışında.")
print(f"📊 Şehir dağılımı:")
print(df_not_istanbul['city'].value_counts().to_string())

================================================================================
🌍 İSTANBUL DIŞINDAKİ MÜŞTERİLER (WHERE NOT city = 'İstanbul')
================================================================================

   first_name last_name     city  age
0        Ayşe     Demir   Ankara   35
1      Mehmet      Kaya    İzmir   42
2         Ali     Çelik    Bursa   25
3      Zeynep    Arslan   Ankara   29
4     Mustafa    Yıldız  Antalya   38
5        Elif     Aydın    İzmir   26
6       Merve     Polat    Konya   33
7        Emre      Kurt   Ankara   27
8       Selin       Şen    İzmir   30
9       Deniz       Koç    Bursa   24
10        Cem   Özdemir  Antalya   40

✅ 11 müşteri İstanbul dışında.
📊 Şehir dağılımı:
city
Ankara     3
İzmir      3
Bursa      2
Antalya    2
Konya      1

### 📋 Örnek 6: Telefon Dışındaki Kategoriler

In [44]:
# Telefon kategorisi dışındaki tüm ürünler
query = """
SELECT name, category, price, stock
FROM products
WHERE NOT category = 'Telefon'
"""

df_not_phones = pd.read_sql_query(query, conn)

print("=" * 80)
print("📦 TELEFON DIŞINDA TÜM ÜRÜNLER (WHERE NOT category = 'Telefon')")
print("=" * 80)
display(df_not_phones)

print(f"\n✅ {len(df_not_phones)} ürün listelendi.")
print(f"📊 Kategori dağılımı:")
print(df_not_phones['category'].value_counts().to_string())

================================================================================
📦 TELEFON DIŞINDA TÜM ÜRÜNLER (WHERE NOT category = 'Telefon')
================================================================================

                    name            category    price  stock
0         MacBook Air M2              Laptop  52999.0     30
1            Dell XPS 15              Laptop  48999.0     25
2               iPad Air              Tablet  24999.0     60
3        Sony WH-1000XM5            Kulaklık  12999.0    100
4   Apple Watch Series 9                Saat  18999.0     40
5    Samsung Galaxy Buds            Kulaklık   3499.0    150
6         LG 55" OLED TV          Televizyon  35999.0     20
7          PlayStation 5        Oyun Konsolu  21999.0     35
8        Nintendo Switch        Oyun Konsolu  11999.0     55
9           Canon EOS R6   Fotoğraf Makinesi  89999.0     15
10         GoPro Hero 12      Aksiyon Kamera  16999.0     40
11             Dyson V15  Elektrikli Süpürge  22999.0     25
12  Xiaomi Robot Süpürge       Robot Süpürge   8999.0     50

✅ 13 ürün listelendi.
📊 Kategori dağılımı:
category
Laptop                2
Kulaklık              2
Oyun Konsolu          2
Tablet                1
Saat                  1
Televizyon            1
Fotoğraf Makinesi     1
Aksiyon Kamera        1
Elektrikli Süpürge    1
Robot Süpürge         1

---

## 🔄 Karmaşık Kombinasyonlar (AND + OR + NOT)

Gerçek hayatta **birden fazla operatörü** bir arada kullanırsınız!

### 📋 Örnek 7: Hedef Müşteri Segmenti (Karmaşık Filtre)

In [45]:
# Büyük şehirlerde (İstanbul VEYA Ankara) ve 25-45 yaş arası müşteriler
query = """
SELECT first_name, last_name, age, city, email
FROM customers
WHERE (city = 'İstanbul' OR city = 'Ankara') 
  AND age BETWEEN 25 AND 45
"""

df_target_segment = pd.read_sql_query(query, conn)

print("=" * 80)
print("🎯 HEDEF MÜŞTERİ SEGMENTİ")
print("   Büyük Şehir (İstanbul/Ankara) + 25-45 Yaş Arası")
print("=" * 80)
display(df_target_segment)

print(f"\n✅ {len(df_target_segment)} hedef müşteri bulundu!")
print(f"📊 Şehir dağılımı:")
print(df_target_segment['city'].value_counts().to_string())
print(f"📊 Ortalama yaş: {df_target_segment['age'].mean():.1f}")
print(f"💼 Bu segment için özel kampanyalar hazırlanabilir!")

================================================================================
🎯 HEDEF MÜŞTERİ SEGMENTİ
   Büyük Şehir (İstanbul/Ankara) + 25-45 Yaş Arası
================================================================================

  first_name last_name  age      city                     email
0      Ahmet    Yılmaz   28  İstanbul    ahmet.yilmaz@gmail.com
1       Ayşe     Demir   35    Ankara    ayse.demir@hotmail.com
2      Fatma     Şahin   31  İstanbul     fatma.sahin@gmail.com
3     Zeynep    Arslan   29    Ankara   zeynep.arslan@gmail.com
4    Hüseyin    Öztürk   45  İstanbul  huseyin.ozturk@gmail.com
5       Emre      Kurt   27    Ankara       emre.kurt@gmail.com
6      Burak      Acar   36  İstanbul      burak.acar@gmail.com

✅ 7 hedef müşteri bulundu!
📊 Şehir dağılımı:
city
İstanbul    4
Ankara      3
📊 Ortalama yaş: 33.0
💼 Bu segment için özel kampanyalar hazırlanabilir!

### 📋 Örnek 8: Satış Fırsatları (Karmaşık Ürün Filtresi)

In [46]:
# Teknoloji ürünleri (Telefon/Laptop/Tablet) + 10.000-50.000 TL arası + Stokta var
query = """
SELECT name, category, price, stock
FROM products
WHERE category IN ('Telefon', 'Laptop', 'Tablet')
  AND price BETWEEN 10000 AND 50000
  AND stock > 10
  AND NOT name LIKE '%Kulak%'
"""

df_sales_opportunities = pd.read_sql_query(query, conn)

print("=" * 80)
print("💼 SATIŞ FIRSATLARI - TEKNOLOJİ ÜRÜNLERİ")
print("   Teknoloji + 10K-50K TL + Yeterli Stok + Kulaklık Hariç")
print("=" * 80)
display(df_sales_opportunities)

if len(df_sales_opportunities) > 0:
    print(f"\n✅ {len(df_sales_opportunities)} ürün satış kampanyası için uygun!")
    print(f"💰 Ortalama fiyat: {df_sales_opportunities['price'].mean():,.0f} ₺")
    print(f"📦 Toplam potansiyel: {(df_sales_opportunities['price'] * df_sales_opportunities['stock']).sum():,.0f} ₺")
else:
    print("\n⚠️ Kriterlere uyan ürün bulunamadı!")

================================================================================
💼 SATIŞ FIRSATLARI - TEKNOLOJİ ÜRÜNLERİ
   Teknoloji + 10K-50K TL + Yeterli Stok + Kulaklık Hariç
================================================================================

                 name category    price  stock
0       iPhone 15 Pro  Telefon  45999.0     50
1  Samsung Galaxy S24  Telefon  38999.0     45
2         Dell XPS 15   Laptop  48999.0     25
3            iPad Air   Tablet  24999.0     60

✅ 4 ürün satış kampanyası için uygun!
💰 Ortalama fiyat: 39,749 ₺
📦 Toplam potansiyel: 6,779,820 ₺

---

## 📊 ORDER BY: Sonuçları Sıralama

**ORDER BY**, sorgu sonuçlarını **belirli bir kolona göre sıralamak** için kullanılır.

<div style="background-color: #E8EAF6; padding: 20px; border-left: 5px solid #5E35B1; border-radius: 10px; margin: 20px 0;">
    <h3 style="color: #4A148C; margin-top: 0;">💡 ORDER BY Kullanımı</h3>
    <p style="font-size: 16px; line-height: 1.7;">
        <strong>ASC</strong> (Ascending) → Küçükten büyüğe (A-Z, 0-9) - <em>Varsayılan</em><br/>
        <strong>DESC</strong> (Descending) → Büyükten küçüğe (Z-A, 9-0)
    </p>
    <pre style="background: linear-gradient(135deg, #E3F2FD 0%, #BBDEFB 100%); color: #0D47A1; padding: 15px; border-radius: 8px; margin-top: 10px; border: 2px solid #90CAF9;">
<code style="font-weight: 600;">SELECT * FROM products
ORDER BY price ASC;   -- En ucuzdan en pahalıya

SELECT * FROM products
ORDER BY price DESC;  -- En pahalıdan en ucuza</code>
    </pre>
</div>

### 📋 Örnek 9: En Genç Müşterilerden En Yaşlıya

In [47]:
# Müşterileri yaşa göre küçükten büyüğe sırala
query = """
SELECT first_name, last_name, age, city
FROM customers
ORDER BY age ASC
LIMIT 10
"""

df_youngest_first = pd.read_sql_query(query, conn)

print("=" * 80)
print("👶 EN GENÇ 10 MÜŞTERİ (ORDER BY age ASC)")
print("=" * 80)
display(df_youngest_first)

print(f"\n📊 Yaş aralığı: {df_youngest_first['age'].min()} - {df_youngest_first['age'].max()} yaş")

================================================================================
👶 EN GENÇ 10 MÜŞTERİ (ORDER BY age ASC)
================================================================================

  first_name last_name  age      city
0      Deniz       Koç   24     Bursa
1        Ali     Çelik   25     Bursa
2       Elif     Aydın   26     İzmir
3       Emre      Kurt   27    Ankara
4      Ahmet    Yılmaz   28  İstanbul
5     Zeynep    Arslan   29    Ankara
6      Selin       Şen   30     İzmir
7      Fatma     Şahin   31  İstanbul
8      Merve     Polat   33     Konya
9       Ayşe     Demir   35    Ankara

📊 Yaş aralığı: 24 - 35 yaş

### 📋 Örnek 10: En Pahalı Ürünler (Top 5)

In [48]:
# En pahalı 5 ürün
query = """
SELECT name, category, price, stock
FROM products
ORDER BY price DESC
LIMIT 5
"""

df_most_expensive = pd.read_sql_query(query, conn)

print("=" * 80)
print("💎 EN PAHALI 5 ÜRÜN (ORDER BY price DESC)")
print("=" * 80)
display(df_most_expensive)

print(f"\n🏆 En pahalı: {df_most_expensive.iloc[0]['name']} - {df_most_expensive.iloc[0]['price']:,.0f} ₺")
print(f"💰 Ortalama fiyat: {df_most_expensive['price'].mean():,.0f} ₺")

================================================================================
💎 EN PAHALI 5 ÜRÜN (ORDER BY price DESC)
================================================================================

                 name           category    price  stock
0        Canon EOS R6  Fotoğraf Makinesi  89999.0     15
1      MacBook Air M2             Laptop  52999.0     30
2         Dell XPS 15             Laptop  48999.0     25
3       iPhone 15 Pro            Telefon  45999.0     50
4  Samsung Galaxy S24            Telefon  38999.0     45

🏆 En pahalı: Canon EOS R6 - 89,999 ₺
💰 Ortalama fiyat: 55,399 ₺

### 📋 Örnek 11: Çoklu Sıralama (İlk Şehir, Sonra Yaş)

In [49]:
# Önce şehre göre alfabetik, sonra yaşa göre küçükten büyüğe
query = """
SELECT first_name, last_name, age, city
FROM customers
ORDER BY city ASC, age ASC
"""

df_multi_sort = pd.read_sql_query(query, conn)

print("=" * 80)
print("📋 ÇOKLU SIRALAMA (Önce Şehir, Sonra Yaş)")
print("=" * 80)
display(df_multi_sort)

print(f"\n💡 Şehirler alfabetik sırada, her şehir içinde yaşa göre sıralı!")

================================================================================
📋 ÇOKLU SIRALAMA (Önce Şehir, Sonra Yaş)
================================================================================

   first_name last_name  age      city
0        Emre      Kurt   27    Ankara
1      Zeynep    Arslan   29    Ankara
2        Ayşe     Demir   35    Ankara
3     Mustafa    Yıldız   38   Antalya
4         Cem   Özdemir   40   Antalya
5       Deniz       Koç   24     Bursa
6         Ali     Çelik   25     Bursa
7       Merve     Polat   33     Konya
8       Ahmet    Yılmaz   28  İstanbul
9       Fatma     Şahin   31  İstanbul
10      Burak      Acar   36  İstanbul
11    Hüseyin    Öztürk   45  İstanbul
12       Elif     Aydın   26     İzmir
13      Selin       Şen   30     İzmir
14     Mehmet      Kaya   42     İzmir

💡 Şehirler alfabetik sırada, her şehir içinde yaşa göre sıralı!

---

## 🎭 DISTINCT: Tekrarları Eleme

**DISTINCT**, **tekrarlanan kayıtları eliyerek** sadece benzersiz değerleri getirir.

<div style="background-color: #F3E5F5; padding: 20px; border-left: 5px solid #9C27B0; border-radius: 10px; margin: 20px 0;">
    <h3 style="color: #6A1B9A; margin-top: 0;">💡 DISTINCT Kullanımı</h3>
    <p style="font-size: 16px; line-height: 1.7;">
        Veritabanında aynı değer birden fazla kez görünüyorsa, <strong>DISTINCT</strong> sadece bir tanesini getirir.
    </p>
    <p style="font-size: 15px; line-height: 1.7; margin-bottom: 0;">
        <strong>Örnek:</strong> "Hangi şehirlerde müşterimiz var?" sorusunu cevaplamak için idealdir!
    </p>
</div>

### 📋 Örnek 12: Benzersiz Şehirler Listesi

In [50]:
# Müşterilerin bulunduğu benzersiz şehirler
query = """
SELECT DISTINCT city
FROM customers
ORDER BY city
"""

df_unique_cities = pd.read_sql_query(query, conn)

print("=" * 80)
print("🏙️ MÜŞTERİLERİMİZİN BULUNDUĞU ŞEHİRLER (DISTINCT city)")
print("=" * 80)
display(df_unique_cities)

print(f"\n✅ Toplamda {len(df_unique_cities)} farklı şehirde müşterimiz var!")
print(f"📍 Şehirler: {', '.join(df_unique_cities['city'].tolist())}")

================================================================================
🏙️ MÜŞTERİLERİMİZİN BULUNDUĞU ŞEHİRLER (DISTINCT city)
================================================================================

       city
0    Ankara
1   Antalya
2     Bursa
3     Konya
4  İstanbul
5     İzmir

✅ Toplamda 6 farklı şehirde müşterimiz var!
📍 Şehirler: Ankara, Antalya, Bursa, Konya, İstanbul, İzmir

### 📋 Örnek 13: Mevcut Ürün Kategorileri

In [51]:
# Stoktaki benzersiz ürün kategorileri
query = """
SELECT DISTINCT category
FROM products
ORDER BY category
"""

df_unique_categories = pd.read_sql_query(query, conn)

print("=" * 80)
print("📦 MEVCUT ÜRÜN KATEGORİLERİ (DISTINCT category)")
print("=" * 80)
display(df_unique_categories)

print(f"\n✅ {len(df_unique_categories)} farklı kategori bulunuyor.")
print(f"📊 Kategoriler: {', '.join(df_unique_categories['category'].tolist())}")

================================================================================
📦 MEVCUT ÜRÜN KATEGORİLERİ (DISTINCT category)
================================================================================

              category
0       Aksiyon Kamera
1   Elektrikli Süpürge
2    Fotoğraf Makinesi
3             Kulaklık
4               Laptop
5         Oyun Konsolu
6        Robot Süpürge
7                 Saat
8               Tablet
9              Telefon
10          Televizyon

✅ 11 farklı kategori bulunuyor.
📊 Kategoriler: Aksiyon Kamera, Elektrikli Süpürge, Fotoğraf Makinesi, Kulaklık, Laptop, Oyun Konsolu, Robot Süpürge, Saat, Tablet, Telefon, Televizyon

---

<div style="background-color: #E3F2FD; padding: 20px; border-radius: 10px; text-align: center; margin: 30px 0;">
    <h2 style="color: #1976D2; margin-top: 0;">🎉 Adım 5 Tamamlandı!</h2>
    <p style="font-size: 16px; color: #0D47A1;">
        Artık karmaşık filtrelemeler ve sıralamalar yapabiliyorsunuz!<br/>
        Bir sonraki adımda <strong>gerçek YBS senaryoları</strong> ve <strong>aggregate fonksiyonlar</strong> ile profesyonel analizler yapacağız! 🚀💼
    </p>
</div>

---
---

# 💼 ADIM 6: Gerçek Hayat YBS Senaryoları ve Analiz

<div style="background: linear-gradient(135deg, #D84315 0%, #BF360C 100%); padding: 25px; border-radius: 15px; color: white; margin: 20px 0;">
    <h2 style="color: white; margin-top: 0;">🎯 Bu Adımda Neler Öğreneceğiz?</h2>
    <ul style="font-size: 16px; line-height: 1.8;">
        <li>✅ <strong>Aggregate Fonksiyonlar</strong> - COUNT, SUM, AVG, MAX, MIN</li>
        <li>✅ <strong>GROUP BY</strong> - Veri gruplama ve analiz</li>
        <li>✅ <strong>HAVING</strong> - Grup filtreleme</li>
        <li>✅ <strong>KPI Hesaplamaları</strong> - İş zekası metrikleri</li>
        <li>✅ <strong>Profesyonel Raporlama</strong> - Dashboard sorguları</li>
        <li>✅ <strong>YBS Karar Destek</strong> - Gerçek senaryolar</li>
    </ul>
</div>

## 🔢 Aggregate Fonksiyonlar: Veriyi Özetleme

**Aggregate (Toplam) Fonksiyonlar**, birden fazla satır üzerinde **hesaplama yaparak tek bir sonuç** döndürür.

<div style="background-color: #FFF3E0; padding: 20px; border-left: 5px solid #F57C00; border-radius: 10px; margin: 20px 0;">
    <h3 style="color: #E65100; margin-top: 0;">💡 5 Temel Aggregate Fonksiyon</h3>
    <table style="width: 100%; margin-top: 10px; border-collapse: collapse;">
        <tr style="background-color: #FFE0B2;">
            <th style="padding: 12px; text-align: left; border: 1px solid #FFAB91;">Fonksiyon</th>
            <th style="padding: 12px; text-align: left; border: 1px solid #FFAB91;">Açıklama</th>
            <th style="padding: 12px; text-align: left; border: 1px solid #FFAB91;">Örnek</th>
        </tr>
        <tr>
            <td style="padding: 10px; border: 1px solid #FFAB91;"><strong>COUNT()</strong></td>
            <td style="padding: 10px; border: 1px solid #FFAB91;">Satır sayısını sayar</td>
            <td style="padding: 10px; border: 1px solid #FFAB91;"><code>COUNT(*)</code> → Toplam kayıt</td>
        </tr>
        <tr style="background-color: #FFF8E1;">
            <td style="padding: 10px; border: 1px solid #FFAB91;"><strong>SUM()</strong></td>
            <td style="padding: 10px; border: 1px solid #FFAB91;">Toplamı hesaplar</td>
            <td style="padding: 10px; border: 1px solid #FFAB91;"><code>SUM(price)</code> → Toplam fiyat</td>
        </tr>
        <tr>
            <td style="padding: 10px; border: 1px solid #FFAB91;"><strong>AVG()</strong></td>
            <td style="padding: 10px; border: 1px solid #FFAB91;">Ortalama hesaplar</td>
            <td style="padding: 10px; border: 1px solid #FFAB91;"><code>AVG(age)</code> → Ortalama yaş</td>
        </tr>
        <tr style="background-color: #FFF8E1;">
            <td style="padding: 10px; border: 1px solid #FFAB91;"><strong>MAX()</strong></td>
            <td style="padding: 10px; border: 1px solid #FFAB91;">En büyük değeri bulur</td>
            <td style="padding: 10px; border: 1px solid #FFAB91;"><code>MAX(price)</code> → En pahalı</td>
        </tr>
        <tr>
            <td style="padding: 10px; border: 1px solid #FFAB91;"><strong>MIN()</strong></td>
            <td style="padding: 10px; border: 1px solid #FFAB91;">En küçük değeri bulur</td>
            <td style="padding: 10px; border: 1px solid #FFAB91;"><code>MIN(age)</code> → En genç</td>
        </tr>
    </table>
</div>

### 📋 Örnek 1: Toplam Müşteri Sayısı (COUNT)

In [52]:
# Veritabanındaki toplam müşteri sayısı
query = """
SELECT 
    COUNT(*) as toplam_musteri,
    COUNT(DISTINCT city) as sehir_sayisi,
    COUNT(DISTINCT email) as benzersiz_email
FROM customers
"""

df_counts = pd.read_sql_query(query, conn)

print("=" * 80)
print("📊 MÜŞTERİ İSTATİSTİKLERİ (COUNT)")
print("=" * 80)
display(df_counts)

print(f"\n✅ Sistemde {df_counts['toplam_musteri'][0]} müşteri kayıtlı")
print(f"🏙️ {df_counts['sehir_sayisi'][0]} farklı şehirde hizmet veriyoruz")
print(f"📧 {df_counts['benzersiz_email'][0]} benzersiz e-posta adresi mevcut")

================================================================================
📊 MÜŞTERİ İSTATİSTİKLERİ (COUNT)
================================================================================

   toplam_musteri  sehir_sayisi  benzersiz_email
0              15             6               15

✅ Sistemde 15 müşteri kayıtlı
🏙️ 6 farklı şehirde hizmet veriyoruz
📧 15 benzersiz e-posta adresi mevcut

### 📋 Örnek 2: Envanter Değeri (SUM)

In [53]:
# Stoktaki toplam ürün değeri (SUM ile hesaplama)
query = """
SELECT 
    SUM(stock) as toplam_stok_adedi,
    SUM(price * stock) as toplam_envanter_degeri
FROM products
"""

df_inventory = pd.read_sql_query(query, conn)

print("=" * 80)
print("💰 ENVANTER DEĞERİ ANALİZİ (SUM)")
print("=" * 80)
display(df_inventory)

toplam_adet = df_inventory['toplam_stok_adedi'][0]
toplam_deger = df_inventory['toplam_envanter_degeri'][0]

print(f"\n📦 Toplam {toplam_adet:,} adet ürün stokta")
print(f"💵 Envanter değeri: {toplam_deger:,.0f} ₺")
print(f"📊 Ürün başına ortalama değer: {(toplam_deger/toplam_adet):,.0f} ₺")

================================================================================
💰 ENVANTER DEĞERİ ANALİZİ (SUM)
================================================================================

   toplam_stok_adedi  toplam_envanter_degeri
0                740              16159260.0

📦 Toplam 740 adet ürün stokta
💵 Envanter değeri: 16,159,260 ₺
📊 Ürün başına ortalama değer: 21,837 ₺

### 📋 Örnek 3: Ortalama Değerler (AVG)

In [54]:
# Ortalama müşteri yaşı ve ortalama ürün fiyatı
query_customers = """
SELECT AVG(age) as ortalama_yas
FROM customers
"""

query_products = """
SELECT AVG(price) as ortalama_fiyat
FROM products
"""

df_avg_age = pd.read_sql_query(query_customers, conn)
df_avg_price = pd.read_sql_query(query_products, conn)

print("=" * 80)
print("📊 ORTALAMA DEĞERLER ANALİZİ (AVG)")
print("=" * 80)
print(f"\n👥 Müşteri Profili:")
print(f"   Ortalama Yaş: {df_avg_age['ortalama_yas'][0]:.1f} yaş")

print(f"\n💰 Ürün Profili:")
print(f"   Ortalama Fiyat: {df_avg_price['ortalama_fiyat'][0]:,.0f} ₺")

# Yaş segmentasyonu
if df_avg_age['ortalama_yas'][0] < 30:
    print(f"   📊 Segment: Genç Müşteri Kitlesi")
elif df_avg_age['ortalama_yas'][0] < 40:
    print(f"   📊 Segment: Orta Yaş Grubu")
else:
    print(f"   📊 Segment: Olgun Müşteri Kitlesi")

================================================================================
📊 ORTALAMA DEĞERLER ANALİZİ (AVG)
================================================================================

👥 Müşteri Profili:
   Ortalama Yaş: 32.6 yaş

💰 Ürün Profili:
   Ortalama Fiyat: 30,432 ₺
   📊 Segment: Orta Yaş Grubu

### 📋 Örnek 4: Maksimum ve Minimum Değerler (MAX, MIN)

In [55]:
# Ürün fiyat aralığı (en ucuz - en pahalı)
query = """
SELECT 
    MIN(price) as en_ucuz,
    MAX(price) as en_pahali,
    (MAX(price) - MIN(price)) as fiyat_farki,
    MIN(stock) as en_dusuk_stok,
    MAX(stock) as en_yuksek_stok
FROM products
"""

df_minmax = pd.read_sql_query(query, conn)

print("=" * 80)
print("📊 FİYAT ve STOK ARALIĞI ANALİZİ (MIN/MAX)")
print("=" * 80)
display(df_minmax)

en_ucuz = df_minmax['en_ucuz'][0]
en_pahali = df_minmax['en_pahali'][0]
fark = df_minmax['fiyat_farki'][0]

print(f"\n💰 Fiyat Aralığı:")
print(f"   En Ucuz: {en_ucuz:,.0f} ₺")
print(f"   En Pahalı: {en_pahali:,.0f} ₺")
print(f"   Fark: {fark:,.0f} ₺ (x{(en_pahali/en_ucuz):.1f} kat)")

print(f"\n📦 Stok Aralığı:")
print(f"   En Düşük: {df_minmax['en_dusuk_stok'][0]} adet")
print(f"   En Yüksek: {df_minmax['en_yuksek_stok'][0]} adet")

================================================================================
📊 FİYAT ve STOK ARALIĞI ANALİZİ (MIN/MAX)
================================================================================

   en_ucuz  en_pahali  fiyat_farki  en_dusuk_stok  en_yuksek_stok
0   3499.0    89999.0      86500.0             15             150

💰 Fiyat Aralığı:
   En Ucuz: 3,499 ₺
   En Pahalı: 89,999 ₺
   Fark: 86,500 ₺ (x25.7 kat)

📦 Stok Aralığı:
   En Düşük: 15 adet
   En Yüksek: 150 adet

### 📋 Örnek 5: Kombine Analiz - Executive Dashboard

In [56]:
# Tüm fonksiyonları birlikte kullanarak kapsamlı analiz
query = """
SELECT 
    COUNT(*) as toplam_urun,
    SUM(stock) as toplam_stok,
    AVG(price) as ortalama_fiyat,
    MIN(price) as en_ucuz_urun,
    MAX(price) as en_pahali_urun,
    SUM(price * stock) as toplam_deger,
    AVG(stock) as ortalama_stok
FROM products
"""

df_dashboard = pd.read_sql_query(query, conn)

print("=" * 80)
print("📊 YÖNETİCİ DASHBOARD - ÜRÜN ANALİZİ")
print("=" * 80)
display(df_dashboard)

print("\n" + "="*80)
print("📈 ÖZET RAPOR")
print("="*80)
print(f"\n🏢 Ürün Portföyü:")
print(f"   • Toplam Ürün Çeşidi: {df_dashboard['toplam_urun'][0]} adet")
print(f"   • Toplam Stok: {df_dashboard['toplam_stok'][0]:,} adet")
print(f"   • Ortalama Stok/Ürün: {df_dashboard['ortalama_stok'][0]:.0f} adet")

print(f"\n💰 Fiyat Analizi:")
print(f"   • Ortalama Fiyat: {df_dashboard['ortalama_fiyat'][0]:,.0f} ₺")
print(f"   • En Ucuz: {df_dashboard['en_ucuz_urun'][0]:,.0f} ₺")
print(f"   • En Pahalı: {df_dashboard['en_pahali_urun'][0]:,.0f} ₺")

print(f"\n📊 Finansal Değer:")
print(f"   • Toplam Envanter: {df_dashboard['toplam_deger'][0]:,.0f} ₺")
print(f"   • Ürün Başına Değer: {(df_dashboard['toplam_deger'][0]/df_dashboard['toplam_urun'][0]):,.0f} ₺")

print("\n✅ Dashboard hazır! Tüm metrikleri tek sorguda aldık!")

================================================================================
📊 YÖNETİCİ DASHBOARD - ÜRÜN ANALİZİ
================================================================================

,toplam_urun,toplam_stok,ortalama_fiyat,en_ucuz_urun,en_pahali_urun,toplam_deger,ortalama_stok
0,15,740,30432.333333,3499.0,89999.0,16159260.0,49.333333

================================================================================
📈 ÖZET RAPOR
================================================================================

🏢 Ürün Portföyü:
   • Toplam Ürün Çeşidi: 15 adet
   • Toplam Stok: 740 adet
   • Ortalama Stok/Ürün: 49 adet

💰 Fiyat Analizi:
   • Ortalama Fiyat: 30,432 ₺
   • En Ucuz: 3,499 ₺
   • En Pahalı: 89,999 ₺

📊 Finansal Değer:
   • Toplam Envanter: 16,159,260 ₺
   • Ürün Başına Değer: 1,077,284 ₺

✅ Dashboard hazır! Tüm metrikleri tek sorguda aldık!

---

## 📊 GROUP BY: Veriyi Gruplama ve Analiz

**GROUP BY**, verileri **belirli bir kolona göre gruplara ayırır** ve her grup için aggregate fonksiyonlar çalıştırır.

<div style="background-color: #E8F5E9; padding: 20px; border-left: 5px solid #43A047; border-radius: 10px; margin: 20px 0;">
    <h3 style="color: #2E7D32; margin-top: 0;">💡 GROUP BY Mantığı</h3>
    <p style="font-size: 16px; line-height: 1.7;">
        <strong>Örnek:</strong> "Her şehirde kaç müşterimiz var?" sorusunu cevaplayabilmek için GROUP BY kullanırız!
    </p>
    <pre style="background: linear-gradient(135deg, #E3F2FD 0%, #BBDEFB 100%); color: #0D47A1; padding: 15px; border-radius: 8px; margin-top: 10px; border: 2px solid #90CAF9;">
<code style="font-weight: 600;">SELECT city, COUNT(*) as musteri_sayisi
FROM customers
GROUP BY city;</code>
    </pre>
    <p style="font-size: 15px; line-height: 1.7; margin-bottom: 0;">
        Bu sorgu, müşterileri <strong>şehre göre gruplar</strong> ve her grup için sayar!
    </p>
</div>

### 📋 Örnek 6: Şehir Bazlı Müşteri Dağılımı

In [57]:
# Her şehirde kaç müşteri var?
query = """
SELECT 
    city as sehir,
    COUNT(*) as musteri_sayisi,
    AVG(age) as ortalama_yas
FROM customers
GROUP BY city
ORDER BY musteri_sayisi DESC
"""

df_city_distribution = pd.read_sql_query(query, conn)

print("=" * 80)
print("🏙️ ŞEHİR BAZLI MÜŞTERİ DAĞILIMI (GROUP BY)")
print("=" * 80)
display(df_city_distribution)

print(f"\n📊 İstatistikler:")
print(f"   • En fazla müşteri: {df_city_distribution.iloc[0]['sehir']} ({df_city_distribution.iloc[0]['musteri_sayisi']} kişi)")
print(f"   • Toplam şehir: {len(df_city_distribution)} şehir")
print(f"   • Ortalama müşteri/şehir: {df_city_distribution['musteri_sayisi'].mean():.1f} kişi")

================================================================================
🏙️ ŞEHİR BAZLI MÜŞTERİ DAĞILIMI (GROUP BY)
================================================================================

      sehir  musteri_sayisi  ortalama_yas
0  İstanbul               4     35.000000
1     İzmir               3     32.666667
2    Ankara               3     30.333333
3     Bursa               2     24.500000
4   Antalya               2     39.000000
5     Konya               1     33.000000

📊 İstatistikler:
   • En fazla müşteri: İstanbul (4 kişi)
   • Toplam şehir: 6 şehir
   • Ortalama müşteri/şehir: 2.5 kişi

### 📋 Örnek 7: Kategori Bazlı Ürün Analizi

In [58]:
# Her kategoride kaç ürün var ve toplam değeri ne?
query = """
SELECT 
    category as kategori,
    COUNT(*) as urun_sayisi,
    SUM(stock) as toplam_stok,
    AVG(price) as ortalama_fiyat,
    MIN(price) as en_ucuz,
    MAX(price) as en_pahali,
    SUM(price * stock) as kategori_degeri
FROM products
GROUP BY category
ORDER BY kategori_degeri DESC
"""

df_category_analysis = pd.read_sql_query(query, conn)

print("=" * 80)
print("📦 KATEGORİ BAZLI ÜRÜN ANALİZİ (GROUP BY)")
print("=" * 80)
display(df_category_analysis)

print(f"\n📊 Kategori Performansı:")
for idx, row in df_category_analysis.iterrows():
    print(f"\n🏷️ {row['kategori']}:")
    print(f"   • Ürün Çeşidi: {row['urun_sayisi']} adet")
    print(f"   • Toplam Stok: {row['toplam_stok']} adet")
    print(f"   • Ortalama Fiyat: {row['ortalama_fiyat']:,.0f} ₺")
    print(f"   • Kategori Değeri: {row['kategori_degeri']:,.0f} ₺")

================================================================================
📦 KATEGORİ BAZLI ÜRÜN ANALİZİ (GROUP BY)
================================================================================

,kategori,urun_sayisi,toplam_stok,ortalama_fiyat,en_ucuz,en_pahali,kategori_degeri
0,Telefon,2,95,42499.0,38999.0,45999.0,4054905.0
1,Laptop,2,55,50999.0,48999.0,52999.0,2814945.0
2,Kulaklık,2,250,8249.0,3499.0,12999.0,1824750.0
3,Tablet,1,60,24999.0,24999.0,24999.0,1499940.0
4,Oyun Konsolu,2,90,16999.0,11999.0,21999.0,1429910.0
5,Fotoğraf Makinesi,1,15,89999.0,89999.0,89999.0,1349985.0
6,Saat,1,40,18999.0,18999.0,18999.0,759960.0
7,Televizyon,1,20,35999.0,35999.0,35999.0,719980.0
8,Aksiyon Kamera,1,40,16999.0,16999.0,16999.0,679960.0
9,Elektrikli Süpürge,1,25,22999.0,22999.0,22999.0,574975.0
10,Robot Süpürge,1,50,8999.0,8999.0,8999.0,449950.0

📊 Kategori Performansı:

🏷️ Telefon:
   • Ürün Çeşidi: 2 adet
   • Toplam Stok: 95 adet
   • Ortalama Fiyat: 42,499 ₺
   • Kategori Değeri: 4,054,905 ₺

🏷️ Laptop:
   • Ürün Çeşidi: 2 adet
   • Toplam Stok: 55 adet
   • Ortalama Fiyat: 50,999 ₺
   • Kategori Değeri: 2,814,945 ₺

🏷️ Kulaklık:
   • Ürün Çeşidi: 2 adet
   • Toplam Stok: 250 adet
   • Ortalama Fiyat: 8,249 ₺
   • Kategori Değeri: 1,824,750 ₺

🏷️ Tablet:
   • Ürün Çeşidi: 1 adet
   • Toplam Stok: 60 adet
   • Ortalama Fiyat: 24,999 ₺
   • Kategori Değeri: 1,499,940 ₺

🏷️ Oyun Konsolu:
   • Ürün Çeşidi: 2 adet
   • Toplam Stok: 90 adet
   • Ortalama Fiyat: 16,999 ₺
   • Kategori Değeri: 1,429,910 ₺

🏷️ Fotoğraf Makinesi:
   • Ürün Çeşidi: 1 adet
   • Toplam Stok: 15 adet
   • Ortalama Fiyat: 89,999 ₺
   • Kategori Değeri: 1,349,985 ₺

🏷️ Saat:
   • Ürün Çeşidi: 1 adet
   • Toplam Stok: 40 adet
   • Ortalama Fiyat: 18,999 ₺
   • Kategori Değeri: 759,960 ₺

🏷️ Televizyon:
   • Ürün Çeşidi: 1 adet
   • Toplam Stok: 20 adet
   • Ortalama Fiyat: 35,999 ₺
   • Kategori Değeri: 719,980 ₺

🏷️ Aksiyon Kamera:
   • Ürün Çeşidi: 1 adet
   • Toplam Stok: 40 adet
   • Ortalama Fiyat: 16,999 ₺
   • Kategori Değeri: 679,960 ₺

🏷️ Elektrikli Süpürge:
   • Ürün Çeşidi: 1 adet
   • Toplam Stok: 25 adet
   • Ortalama Fiyat: 22,999 ₺
   • Kategori Değeri: 574,975 ₺

🏷️ Robot Süpürge:
   • Ürün Çeşidi: 1 adet
   • Toplam Stok: 50 adet
   • Ortalama Fiyat: 8,999 ₺
   • Kategori Değeri: 449,950 ₺

### 📋 Örnek 8: Şehir ve Yaş Segmenti Analizi

In [59]:
# Yaş segmentlerine göre şehir bazlı analiz
query = """
SELECT 
    city as sehir,
    CASE 
        WHEN age < 25 THEN 'Genç (18-24)'
        WHEN age < 35 THEN 'Genç Yetişkin (25-34)'
        WHEN age < 45 THEN 'Orta Yaş (35-44)'
        ELSE 'Olgun (45+)'
    END as yas_segmenti,
    COUNT(*) as kisi_sayisi
FROM customers
GROUP BY city, yas_segmenti
ORDER BY city, yas_segmenti
"""

df_segment_analysis = pd.read_sql_query(query, conn)

print("=" * 80)
print("👥 ŞEHİR ve YAŞ SEGMENTİ ANALİZİ (GROUP BY + CASE)")
print("=" * 80)
display(df_segment_analysis)

print(f"\n💡 Her şehir için yaş segmenti dağılımını görebiliyoruz!")
print(f"📊 Bu analiz ile hedefli pazarlama yapabiliriz!")

================================================================================
👥 ŞEHİR ve YAŞ SEGMENTİ ANALİZİ (GROUP BY + CASE)
================================================================================

       sehir           yas_segmenti  kisi_sayisi
0     Ankara  Genç Yetişkin (25-34)            2
1     Ankara       Orta Yaş (35-44)            1
2    Antalya       Orta Yaş (35-44)            2
3      Bursa           Genç (18-24)            1
4      Bursa  Genç Yetişkin (25-34)            1
5      Konya  Genç Yetişkin (25-34)            1
6   İstanbul  Genç Yetişkin (25-34)            2
7   İstanbul            Olgun (45+)            1
8   İstanbul       Orta Yaş (35-44)            1
9      İzmir  Genç Yetişkin (25-34)            2
10     İzmir       Orta Yaş (35-44)            1

💡 Her şehir için yaş segmenti dağılımını görebiliyoruz!
📊 Bu analiz ile hedefli pazarlama yapabiliriz!

---

## 🔍 HAVING: Grup Filtreleme

**HAVING**, GROUP BY ile oluşturulan **grupları filtrelemek** için kullanılır. WHERE'den farkı: WHERE satırları, HAVING grupları filtreler!

<div style="background-color: #FCE4EC; padding: 20px; border-left: 5px solid #C2185B; border-radius: 10px; margin: 20px 0;">
    <h3 style="color: #880E4F; margin-top: 0;">💡 WHERE vs HAVING</h3>
    <table style="width: 100%; margin-top: 10px; border-collapse: collapse;">
        <tr style="background-color: #F8BBD0;">
            <th style="padding: 12px; text-align: left; border: 1px solid #F48FB1;">Özellik</th>
            <th style="padding: 12px; text-align: left; border: 1px solid #F48FB1;">WHERE</th>
            <th style="padding: 12px; text-align: left; border: 1px solid #F48FB1;">HAVING</th>
        </tr>
        <tr>
            <td style="padding: 10px; border: 1px solid #F48FB1;"><strong>Ne zaman?</strong></td>
            <td style="padding: 10px; border: 1px solid #F48FB1;">Gruplama ÖNCE</td>
            <td style="padding: 10px; border: 1px solid #F48FB1;">Gruplama SONRA</td>
        </tr>
        <tr style="background-color: #FCE4EC;">
            <td style="padding: 10px; border: 1px solid #F48FB1;"><strong>Neyi filtreler?</strong></td>
            <td style="padding: 10px; border: 1px solid #F48FB1;">Satırları</td>
            <td style="padding: 10px; border: 1px solid #F48FB1;">Grupları</td>
        </tr>
        <tr>
            <td style="padding: 10px; border: 1px solid #F48FB1;"><strong>Örnek</strong></td>
            <td style="padding: 10px; border: 1px solid #F48FB1;"><code>WHERE age > 30</code></td>
            <td style="padding: 10px; border: 1px solid #F48FB1;"><code>HAVING COUNT(*) > 5</code></td>
        </tr>
    </table>
</div>

### 📋 Örnek 9: Yüksek Müşteri Sayısına Sahip Şehirler

In [60]:
# Sadece 2'den fazla müşterisi olan şehirler
query = """
SELECT 
    city as sehir,
    COUNT(*) as musteri_sayisi,
    AVG(age) as ortalama_yas
FROM customers
GROUP BY city
HAVING COUNT(*) > 2
ORDER BY musteri_sayisi DESC
"""

df_high_customer_cities = pd.read_sql_query(query, conn)

print("=" * 80)
print("🏙️ YÜKSEK MÜŞTERİ POTANSİYELİNE SAHİP ŞEHİRLER (HAVING)")
print("   Kriterler: 2'den fazla müşteri")
print("=" * 80)
display(df_high_customer_cities)

print(f"\n✅ {len(df_high_customer_cities)} şehir bu kritere uyuyor")
print(f"💼 Bu şehirlere özel kampanyalar düzenlenebilir!")

================================================================================
🏙️ YÜKSEK MÜŞTERİ POTANSİYELİNE SAHİP ŞEHİRLER (HAVING)
   Kriterler: 2'den fazla müşteri
================================================================================

      sehir  musteri_sayisi  ortalama_yas
0  İstanbul               4     35.000000
1     İzmir               3     32.666667
2    Ankara               3     30.333333

✅ 3 şehir bu kritere uyuyor
💼 Bu şehirlere özel kampanyalar düzenlenebilir!

### 📋 Örnek 10: Yüksek Değerli Ürün Kategorileri

In [61]:
# Sadece toplam değeri 500.000 TL'den fazla olan kategoriler
query = """
SELECT 
    category as kategori,
    COUNT(*) as urun_sayisi,
    SUM(price * stock) as toplam_deger,
    AVG(price) as ortalama_fiyat
FROM products
GROUP BY category
HAVING SUM(price * stock) > 500000
ORDER BY toplam_deger DESC
"""

df_high_value_categories = pd.read_sql_query(query, conn)

print("=" * 80)
print("💎 YÜKSEK DEĞERLİ ÜRÜN KATEGORİLERİ (HAVING)")
print("   Kriterler: Toplam değer > 500.000 ₺")
print("=" * 80)
display(df_high_value_categories)

if len(df_high_value_categories) > 0:
    print(f"\n✅ {len(df_high_value_categories)} kategori bu kritere uyuyor")
    print(f"💰 Bu kategorilere özel odaklanma gerekli!")
    print(f"📊 Toplam değer: {df_high_value_categories['toplam_deger'].sum():,.0f} ₺")
else:
    print("\n⚠️ Kriterlere uyan kategori bulunamadı")

================================================================================
💎 YÜKSEK DEĞERLİ ÜRÜN KATEGORİLERİ (HAVING)
   Kriterler: Toplam değer > 500.000 ₺
================================================================================

             kategori  urun_sayisi  toplam_deger  ortalama_fiyat
0             Telefon            2     4054905.0         42499.0
1              Laptop            2     2814945.0         50999.0
2            Kulaklık            2     1824750.0          8249.0
3              Tablet            1     1499940.0         24999.0
4        Oyun Konsolu            2     1429910.0         16999.0
5   Fotoğraf Makinesi            1     1349985.0         89999.0
6                Saat            1      759960.0         18999.0
7          Televizyon            1      719980.0         35999.0
8      Aksiyon Kamera            1      679960.0         16999.0
9  Elektrikli Süpürge            1      574975.0         22999.0

✅ 10 kategori bu kritere uyuyor
💰 Bu kategorilere özel odaklanma gerekli!
📊 Toplam değer: 15,709,310 ₺

### 📋 Örnek 11: WHERE + GROUP BY + HAVING Kombinasyonu

In [62]:
# Karmaşık analiz: 10.000 TL üzeri ürünlerin kategori analizi
# Sadece ortalama fiyatı 20.000 TL'den fazla olan kategoriler
query = """
SELECT 
    category as kategori,
    COUNT(*) as premium_urun_sayisi,
    AVG(price) as ortalama_fiyat,
    MIN(price) as en_ucuz,
    MAX(price) as en_pahali,
    SUM(stock) as toplam_stok
FROM products
WHERE price >= 10000
GROUP BY category
HAVING AVG(price) > 20000
ORDER BY ortalama_fiyat DESC
"""

df_premium_analysis = pd.read_sql_query(query, conn)

print("=" * 80)
print("💎 PREMİUM ÜRÜN KATEGORİLERİ - DETAYLI ANALİZ")
print("   WHERE: Fiyat >= 10.000 ₺")
print("   HAVING: Ortalama fiyat > 20.000 ₺")
print("=" * 80)
display(df_premium_analysis)

if len(df_premium_analysis) > 0:
    print(f"\n🎯 {len(df_premium_analysis)} premium kategori bulundu!")
    for idx, row in df_premium_analysis.iterrows():
        print(f"\n📦 {row['kategori']}:")
        print(f"   • Ürün Sayısı: {row['premium_urun_sayisi']}")
        print(f"   • Ortalama Fiyat: {row['ortalama_fiyat']:,.0f} ₺")
        print(f"   • Fiyat Aralığı: {row['en_ucuz']:,.0f} - {row['en_pahali']:,.0f} ₺")
else:
    print("\n💡 Premium kategoriler için asgari eşik yükseltilebilir!")

================================================================================
💎 PREMİUM ÜRÜN KATEGORİLERİ - DETAYLI ANALİZ
   WHERE: Fiyat >= 10.000 ₺
   HAVING: Ortalama fiyat > 20.000 ₺
================================================================================

,kategori,premium_urun_sayisi,ortalama_fiyat,en_ucuz,en_pahali,toplam_stok
0,Fotoğraf Makinesi,1,89999.0,89999.0,89999.0,15
1,Laptop,2,50999.0,48999.0,52999.0,55
2,Telefon,2,42499.0,38999.0,45999.0,95
3,Televizyon,1,35999.0,35999.0,35999.0,20
4,Tablet,1,24999.0,24999.0,24999.0,60
5,Elektrikli Süpürge,1,22999.0,22999.0,22999.0,25

🎯 6 premium kategori bulundu!

📦 Fotoğraf Makinesi:
   • Ürün Sayısı: 1
   • Ortalama Fiyat: 89,999 ₺
   • Fiyat Aralığı: 89,999 - 89,999 ₺

📦 Laptop:
   • Ürün Sayısı: 2
   • Ortalama Fiyat: 50,999 ₺
   • Fiyat Aralığı: 48,999 - 52,999 ₺

📦 Telefon:
   • Ürün Sayısı: 2
   • Ortalama Fiyat: 42,499 ₺
   • Fiyat Aralığı: 38,999 - 45,999 ₺

📦 Televizyon:
   • Ürün Sayısı: 1
   • Ortalama Fiyat: 35,999 ₺
   • Fiyat Aralığı: 35,999 - 35,999 ₺

📦 Tablet:
   • Ürün Sayısı: 1
   • Ortalama Fiyat: 24,999 ₺
   • Fiyat Aralığı: 24,999 - 24,999 ₺

📦 Elektrikli Süpürge:
   • Ürün Sayısı: 1
   • Ortalama Fiyat: 22,999 ₺
   • Fiyat Aralığı: 22,999 - 22,999 ₺

---

## 💼 Gerçek Hayat YBS Senaryoları

Artık öğrendiğimiz tüm becerileri **gerçek iş problemlerinde** kullanalım!

### 📋 Senaryo 1: Satış Performans Raporu (Management Dashboard)

In [66]:
# YÖNETİCİ DASHBOARD: Sipariş Analizi
query = """
SELECT 
    o.order_id,
    c.first_name || ' ' || c.last_name as musteri,
    c.city,
    o.order_date,
    COUNT(oi.item_id) as urun_adedi,
    SUM(oi.quantity * oi.unit_price) as toplam_tutar,
    AVG(oi.unit_price) as ortalama_urun_fiyati
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY o.order_id, c.first_name, c.last_name, c.city, o.order_date
ORDER BY toplam_tutar DESC
LIMIT 10
"""

df_sales_report = pd.read_sql_query(query, conn)

print("=" * 80)
print("📊 SATIŞ PERFORMANS RAPORU - TOP 10 SİPARİŞ")
print("=" * 80)
display(df_sales_report)

toplam_ciro = df_sales_report['toplam_tutar'].sum()
print(f"\n💰 Top 10 Sipariş Cirosu: {toplam_ciro:,.0f} ₺")
print(f"📦 Ortalama Sepet Değeri: {df_sales_report['toplam_tutar'].mean():,.0f} ₺")
print(f"🎯 En Yüksek Sipariş: {df_sales_report.iloc[0]['musteri']} - {df_sales_report.iloc[0]['toplam_tutar']:,.0f} ₺")

================================================================================
📊 SATIŞ PERFORMANS RAPORU - TOP 10 SİPARİŞ
================================================================================

,order_id,musteri,city,order_date,urun_adedi,toplam_tutar,ortalama_urun_fiyati
0,10,Mehmet Kaya,İzmir,2026-01-12,1,89999.0,89999.0
1,3,Mehmet Kaya,İzmir,2025-12-01,1,52999.0,52999.0
2,6,Ali Çelik,Bursa,2025-12-20,1,48999.0,48999.0
3,1,Ahmet Yılmaz,İstanbul,2025-11-15,1,45999.0,45999.0
4,16,Burak Acar,İstanbul,2026-01-17,1,45999.0,45999.0
5,2,Ayşe Demir,Ankara,2025-11-20,1,38999.0,38999.0
6,8,Mustafa Yıldız,Antalya,2026-01-08,1,35999.0,35999.0
7,5,Fatma Şahin,İstanbul,2025-12-15,1,24999.0,24999.0
8,17,Deniz Koç,Bursa,2026-01-18,1,24999.0,24999.0
9,14,Emre Kurt,Ankara,2026-01-16,1,22999.0,22999.0

💰 Top 10 Sipariş Cirosu: 431,990 ₺
📦 Ortalama Sepet Değeri: 43,199 ₺
🎯 En Yüksek Sipariş: Mehmet Kaya - 89,999 ₺

### 📋 Senaryo 2: Müşteri Segmentasyonu (RFM Analizi)

In [71]:
# MÜŞTERİ SEGMENTASYONU: Sipariş sayısı ve toplam harcama
query = """
SELECT 
    c.customer_id,
    c.first_name || ' ' || c.last_name as musteri,
    c.city,
    c.age,
    COUNT(DISTINCT o.order_id) as siparis_sayisi,
    SUM(oi.quantity * oi.unit_price) as toplam_harcama,
    AVG(oi.quantity * oi.unit_price) as ortalama_siparis_tutari,
    CASE 
        WHEN SUM(oi.quantity * oi.unit_price) > 100000 THEN 'VIP'
        WHEN SUM(oi.quantity * oi.unit_price) > 50000 THEN 'Premium'
        WHEN SUM(oi.quantity * oi.unit_price) > 20000 THEN 'Standart'
        ELSE 'Yeni Müşteri'
    END as musteri_segmenti
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
LEFT JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.first_name, c.last_name, c.city, c.age
ORDER BY toplam_harcama DESC
"""

df_customer_segments = pd.read_sql_query(query, conn)

print("=" * 80)
print("👥 MÜŞTERİ SEGMENTASYONU ANALİZİ")
print("=" * 80)
display(df_customer_segments)

print(f"\n📊 Segment Dağılımı:")
segment_counts = df_customer_segments['musteri_segmenti'].value_counts()
for segment, count in segment_counts.items():
    print(f"   • {segment}: {count} müşteri")

print(f"\n💰 En Değerli Müşteri: {df_customer_segments.iloc[0]['musteri']}")
print(f"   Harcama: {df_customer_segments.iloc[0]['toplam_harcama']:,.0f} ₺")
print(f"   Sipariş: {df_customer_segments.iloc[0]['siparis_sayisi']} adet")

================================================================================
👥 MÜŞTERİ SEGMENTASYONU ANALİZİ
================================================================================

,customer_id,musteri,city,age,siparis_sayisi,toplam_harcama,ortalama_siparis_tutari,musteri_segmenti
0,3,Mehmet Kaya,İzmir,42,2,142998.0,71499.0,VIP
1,1,Ahmet Yılmaz,İstanbul,28,2,58998.0,29499.0,Premium
2,2,Ayşe Demir,Ankara,35,2,50998.0,25499.0,Premium
3,5,Ali Çelik,Bursa,25,1,48999.0,48999.0,Standart
4,13,Burak Acar,İstanbul,36,1,45999.0,45999.0,Standart
5,7,Mustafa Yıldız,Antalya,38,1,35999.0,35999.0,Standart
6,4,Fatma Şahin,İstanbul,31,1,24999.0,24999.0,Standart
7,14,Deniz Koç,Bursa,24,1,24999.0,24999.0,Standart
8,11,Emre Kurt,Ankara,27,1,22999.0,22999.0,Standart
9,9,Hüseyin Öztürk,İstanbul,45,1,21999.0,21999.0,Standart
10,6,Zeynep Arslan,Ankara,29,1,18999.0,18999.0,Yeni Müşteri
11,10,Merve Polat,Konya,33,1,16999.0,16999.0,Yeni Müşteri
12,15,Cem Özdemir,Antalya,40,1,12999.0,12999.0,Yeni Müşteri
13,12,Selin Şen,İzmir,30,1,8999.0,8999.0,Yeni Müşteri
14,8,Elif Aydın,İzmir,26,1,6998.0,6998.0,Yeni Müşteri

📊 Segment Dağılımı:
   • Standart: 7 müşteri
   • Yeni Müşteri: 5 müşteri
   • Premium: 2 müşteri
   • VIP: 1 müşteri

💰 En Değerli Müşteri: Mehmet Kaya
   Harcama: 142,998 ₺
   Sipariş: 2 adet

### 📋 Senaryo 3: Ürün Satış Performansı (En Çok Satanlar)

In [73]:
# EN ÇOK SATAN ÜRÜNLER ANALİZİ
query = """
SELECT 
    p.name as urun,
    p.category as kategori,
    p.price as liste_fiyati,
    COUNT(DISTINCT oi.order_id) as siparis_sayisi,
    SUM(oi.quantity) as satilan_adet,
    SUM(oi.quantity * oi.unit_price) as toplam_gelir,
    AVG(oi.unit_price) as ortalama_satis_fiyati,
    p.stock as guncel_stok
FROM products p
LEFT JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_id, p.name, p.category, p.price, p.stock
HAVING SUM(oi.quantity) > 0
ORDER BY toplam_gelir DESC
LIMIT 10
"""

df_best_sellers = pd.read_sql_query(query, conn)

print("=" * 80)
print("🏆 EN ÇOK SATAN 10 ÜRÜN")
print("=" * 80)
display(df_best_sellers)

print(f"\n📊 Performans Özeti:")
print(f"   • Toplam Gelir: {df_best_sellers['toplam_gelir'].sum():,.0f} ₺")
print(f"   • Toplam Satış: {df_best_sellers['satilan_adet'].sum()} adet")
print(f"   • Ortalama Ürün Geliri: {df_best_sellers['toplam_gelir'].mean():,.0f} ₺")

print(f"\n🥇 1. Sıra: {df_best_sellers.iloc[0]['urun']}")
print(f"   Gelir: {df_best_sellers.iloc[0]['toplam_gelir']:,.0f} ₺")
print(f"   Satış: {df_best_sellers.iloc[0]['satilan_adet']} adet")

================================================================================
🏆 EN ÇOK SATAN 10 ÜRÜN
================================================================================

,urun,kategori,liste_fiyati,siparis_sayisi,satilan_adet,toplam_gelir,ortalama_satis_fiyati,guncel_stok
0,iPhone 15 Pro,Telefon,45999.0,2,2,91998.0,45999.0,50
1,Canon EOS R6,Fotoğraf Makinesi,89999.0,1,1,89999.0,89999.0,15
2,MacBook Air M2,Laptop,52999.0,1,1,52999.0,52999.0,30
3,iPad Air,Tablet,24999.0,2,2,49998.0,24999.0,60
4,Dell XPS 15,Laptop,48999.0,1,1,48999.0,48999.0,25
5,Samsung Galaxy S24,Telefon,38999.0,1,1,38999.0,38999.0,45
6,"LG 55"" OLED TV",Televizyon,35999.0,1,1,35999.0,35999.0,20
7,Sony WH-1000XM5,Kulaklık,12999.0,2,2,25998.0,12999.0,100
8,Dyson V15,Elektrikli Süpürge,22999.0,1,1,22999.0,22999.0,25
9,PlayStation 5,Oyun Konsolu,21999.0,1,1,21999.0,21999.0,35

📊 Performans Özeti:
   • Toplam Gelir: 479,987 ₺
   • Toplam Satış: 13 adet
   • Ortalama Ürün Geliri: 47,999 ₺

🥇 1. Sıra: iPhone 15 Pro
   Gelir: 91,998 ₺
   Satış: 2 adet

### 📋 Senaryo 4: Şehir Bazlı Satış Analizi (Coğrafi Performans)

In [74]:
# COĞRAFİ SATIŞ PERFORMANSI
query = """
SELECT 
    c.city as sehir,
    COUNT(DISTINCT c.customer_id) as musteri_sayisi,
    COUNT(DISTINCT o.order_id) as siparis_sayisi,
    SUM(oi.quantity * oi.unit_price) as toplam_ciro,
    AVG(oi.quantity * oi.unit_price) as ortalama_siparis,
    ROUND(1.0 * COUNT(DISTINCT o.order_id) / COUNT(DISTINCT c.customer_id), 2) as musteri_basina_siparis
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
LEFT JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.city
HAVING SUM(oi.quantity * oi.unit_price) > 0
ORDER BY toplam_ciro DESC
"""

df_city_performance = pd.read_sql_query(query, conn)

print("=" * 80)
print("🗺️ ŞEHİR BAZLI SATIŞ PERFORMANSI")
print("=" * 80)
display(df_city_performance)

print(f"\n📊 Coğrafi Performans Özeti:")
print(f"   • En Yüksek Ciro: {df_city_performance.iloc[0]['sehir']} - {df_city_performance.iloc[0]['toplam_ciro']:,.0f} ₺")
print(f"   • Toplam Ciro: {df_city_performance['toplam_ciro'].sum():,.0f} ₺")
print(f"   • En Aktif Şehir: {df_city_performance.iloc[0]['sehir']} ({df_city_performance.iloc[0]['siparis_sayisi']} sipariş)")

print(f"\n💡 Strateji Önerisi:")
top_city = df_city_performance.iloc[0]['sehir']
print(f"   • {top_city} en yüksek potansiyele sahip!")
print(f"   • Burada özel kampanyalar düzenlenebilir.")

================================================================================
🗺️ ŞEHİR BAZLI SATIŞ PERFORMANSI
================================================================================

,sehir,musteri_sayisi,siparis_sayisi,toplam_ciro,ortalama_siparis,musteri_basina_siparis
0,İzmir,3,4,158995.0,39748.75,1.33
1,İstanbul,4,5,151995.0,30399.00,1.25
2,Ankara,3,4,92996.0,23249.00,1.33
3,Bursa,2,2,73998.0,36999.00,1.00
4,Antalya,2,2,48998.0,24499.00,1.00
5,Konya,1,1,16999.0,16999.00,1.00

📊 Coğrafi Performans Özeti:
   • En Yüksek Ciro: İzmir - 158,995 ₺
   • Toplam Ciro: 543,981 ₺
   • En Aktif Şehir: İzmir (4 sipariş)

💡 Strateji Önerisi:
   • İzmir en yüksek potansiyele sahip!
   • Burada özel kampanyalar düzenlenebilir.

### 📋 Senaryo 5: KPI Dashboard (Temel İş Metrikleri)

In [75]:
# KPI DASHBOARD - Tüm Metrikler Bir Arada
print("=" * 80)
print("📊 YÖNETİCİ KPI DASHBOARD")
print("=" * 80)

# 1. Müşteri Metrikleri
query_customers = """
SELECT 
    COUNT(*) as toplam_musteri,
    COUNT(DISTINCT city) as sehir_sayisi,
    AVG(age) as ortalama_yas
FROM customers
"""
df_kpi_customers = pd.read_sql_query(query_customers, conn)

# 2. Ürün Metrikleri
query_products = """
SELECT 
    COUNT(*) as toplam_urun,
    COUNT(DISTINCT category) as kategori_sayisi,
    SUM(stock) as toplam_stok,
    SUM(price * stock) as envanter_degeri
FROM products
"""
df_kpi_products = pd.read_sql_query(query_products, conn)

# 3. Satış Metrikleri
query_sales = """
SELECT 
    COUNT(DISTINCT o.order_id) as toplam_siparis,
    SUM(oi.quantity) as toplam_satis_adedi,
    SUM(oi.quantity * oi.unit_price) as toplam_ciro,
    AVG(oi.quantity * oi.unit_price) as ortalama_siparis_tutari
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
"""
df_kpi_sales = pd.read_sql_query(query_sales, conn)

# KPI'ları göster
print("\n🔵 MÜŞTERİ KPI'LARI")
print("-" * 80)
print(f"   • Toplam Müşteri: {df_kpi_customers['toplam_musteri'][0]:,}")
print(f"   • Aktif Şehir: {df_kpi_customers['sehir_sayisi'][0]}")
print(f"   • Ortalama Yaş: {df_kpi_customers['ortalama_yas'][0]:.1f}")

print("\n🔵 ÜRÜN KPI'LARI")
print("-" * 80)
print(f"   • Ürün Çeşidi: {df_kpi_products['toplam_urun'][0]:,}")
print(f"   • Kategori Sayısı: {df_kpi_products['kategori_sayisi'][0]}")
print(f"   • Toplam Stok: {df_kpi_products['toplam_stok'][0]:,} adet")
print(f"   • Envanter Değeri: {df_kpi_products['envanter_degeri'][0]:,.0f} ₺")

print("\n🔵 SATIŞ KPI'LARI")
print("-" * 80)
print(f"   • Toplam Sipariş: {df_kpi_sales['toplam_siparis'][0]:,}")
print(f"   • Satılan Ürün: {df_kpi_sales['toplam_satis_adedi'][0]:,} adet")
print(f"   • Toplam Ciro: {df_kpi_sales['toplam_ciro'][0]:,.0f} ₺")
print(f"   • Ortalama Sepet: {df_kpi_sales['ortalama_siparis_tutari'][0]:,.0f} ₺")

# Hesaplanan Metrikler
conversion_rate = (df_kpi_sales['toplam_siparis'][0] / df_kpi_customers['toplam_musteri'][0]) * 100
print("\n🔵 HESAPLANAN METRİKLER")
print("-" * 80)
print(f"   • Dönüşüm Oranı: %{conversion_rate:.1f}")
print(f"   • Müşteri Başına Ortalama Ciro: {df_kpi_sales['toplam_ciro'][0] / df_kpi_customers['toplam_musteri'][0]:,.0f} ₺")
print(f"   • Stok Devir Hızı: {df_kpi_sales['toplam_satis_adedi'][0] / df_kpi_products['toplam_stok'][0]:.2%}")

================================================================================
📊 YÖNETİCİ KPI DASHBOARD
================================================================================

🔵 MÜŞTERİ KPI'LARI
--------------------------------------------------------------------------------
   • Toplam Müşteri: 15
   • Aktif Şehir: 6
   • Ortalama Yaş: 32.6

🔵 ÜRÜN KPI'LARI
--------------------------------------------------------------------------------
   • Ürün Çeşidi: 15
   • Kategori Sayısı: 11
   • Toplam Stok: 740 adet
   • Envanter Değeri: 16,159,260 ₺

🔵 SATIŞ KPI'LARI
--------------------------------------------------------------------------------
   • Toplam Sipariş: 18
   • Satılan Ürün: 19 adet
   • Toplam Ciro: 543,981 ₺
   • Ortalama Sepet: 30,221 ₺

🔵 HESAPLANAN METRİKLER
--------------------------------------------------------------------------------
   • Dönüşüm Oranı: %120.0
   • Müşteri Başına Ortalama Ciro: 36,265 ₺
   • Stok Devir Hızı: 2.57%

---

## 🎓 SQL Cheat Sheet - Hızlı Referans

In [76]:
# SQL CHEAT SHEET - Görsel Referans
cheat_sheet = """
<div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 15px; color: white; margin: 20px 0;">
    <h2 style="color: white; text-align: center; margin-top: 0;">📚 SQL CHEAT SHEET</h2>
    
    <div style="background: rgba(255,255,255,0.1); padding: 20px; border-radius: 10px; margin: 15px 0;">
        <h3 style="color: #FFD700; margin-top: 0;">📖 Temel Komutlar</h3>
        <table style="width: 100%; color: white;">
            <tr>
                <td style="padding: 8px;"><strong>SELECT</strong></td>
                <td style="padding: 8px;">Veri okuma</td>
                <td style="padding: 8px;"><code style="background: rgba(100,181,246,0.3); padding: 4px 8px; border-radius: 4px; color: #90CAF9;">SELECT * FROM table</code></td>
            </tr>
            <tr>
                <td style="padding: 8px;"><strong>WHERE</strong></td>
                <td style="padding: 8px;">Filtreleme</td>
                <td style="padding: 8px;"><code style="background: rgba(100,181,246,0.3); padding: 4px 8px; border-radius: 4px; color: #90CAF9;">WHERE age > 25</code></td>
            </tr>
            <tr>
                <td style="padding: 8px;"><strong>ORDER BY</strong></td>
                <td style="padding: 8px;">Sıralama</td>
                <td style="padding: 8px;"><code style="background: rgba(100,181,246,0.3); padding: 4px 8px; border-radius: 4px; color: #90CAF9;">ORDER BY price DESC</code></td>
            </tr>
            <tr>
                <td style="padding: 8px;"><strong>LIMIT</strong></td>
                <td style="padding: 8px;">Kayıt sayısı</td>
                <td style="padding: 8px;"><code style="background: rgba(100,181,246,0.3); padding: 4px 8px; border-radius: 4px; color: #90CAF9;">LIMIT 10</code></td>
            </tr>
        </table>
    </div>
    
    <div style="background: rgba(255,255,255,0.1); padding: 20px; border-radius: 10px; margin: 15px 0;">
        <h3 style="color: #FFD700; margin-top: 0;">🔢 Aggregate Fonksiyonlar</h3>
        <table style="width: 100%; color: white;">
            <tr>
                <td style="padding: 8px;"><strong>COUNT(*)</strong></td>
                <td style="padding: 8px;">Satır sayısı</td>
            </tr>
            <tr>
                <td style="padding: 8px;"><strong>SUM(kolon)</strong></td>
                <td style="padding: 8px;">Toplam</td>
            </tr>
            <tr>
                <td style="padding: 8px;"><strong>AVG(kolon)</strong></td>
                <td style="padding: 8px;">Ortalama</td>
            </tr>
            <tr>
                <td style="padding: 8px;"><strong>MAX(kolon)</strong></td>
                <td style="padding: 8px;">En büyük</td>
            </tr>
            <tr>
                <td style="padding: 8px;"><strong>MIN(kolon)</strong></td>
                <td style="padding: 8px;">En küçük</td>
            </tr>
        </table>
    </div>
    
    <div style="background: rgba(255,255,255,0.1); padding: 20px; border-radius: 10px; margin: 15px 0;">
        <h3 style="color: #FFD700; margin-top: 0;">🎯 Operatörler</h3>
        <table style="width: 100%; color: white;">
            <tr>
                <td style="padding: 8px;"><strong>AND / OR / NOT</strong></td>
                <td style="padding: 8px;">Mantıksal</td>
            </tr>
            <tr>
                <td style="padding: 8px;"><strong>LIKE</strong></td>
                <td style="padding: 8px;">Metin arama (%, _)</td>
            </tr>
            <tr>
                <td style="padding: 8px;"><strong>IN</strong></td>
                <td style="padding: 8px;">Çoklu değer</td>
            </tr>
            <tr>
                <td style="padding: 8px;"><strong>BETWEEN</strong></td>
                <td style="padding: 8px;">Aralık</td>
            </tr>
            <tr>
                <td style="padding: 8px;"><strong>DISTINCT</strong></td>
                <td style="padding: 8px;">Tekrarsız</td>
            </tr>
        </table>
    </div>
    
    <div style="background: rgba(255,255,255,0.1); padding: 20px; border-radius: 10px; margin: 15px 0;">
        <h3 style="color: #FFD700; margin-top: 0;">📊 Gruplama</h3>
        <table style="width: 100%; color: white;">
            <tr>
                <td style="padding: 8px;"><strong>GROUP BY</strong></td>
                <td style="padding: 8px;">Gruplama</td>
            </tr>
            <tr>
                <td style="padding: 8px;"><strong>HAVING</strong></td>
                <td style="padding: 8px;">Grup filtreleme</td>
            </tr>
        </table>
    </div>
    
    <div style="background: rgba(255,255,255,0.1); padding: 20px; border-radius: 10px; margin: 15px 0;">
        <h3 style="color: #FFD700; margin-top: 0;">🔗 Birleştirme</h3>
        <table style="width: 100%; color: white;">
            <tr>
                <td style="padding: 8px;"><strong>JOIN</strong></td>
                <td style="padding: 8px;">İki tabloyu birleştir</td>
            </tr>
            <tr>
                <td style="padding: 8px;"><strong>LEFT JOIN</strong></td>
                <td style="padding: 8px;">Sol tablo hepsini getir</td>
            </tr>
        </table>
    </div>
</div>
"""

display(HTML(cheat_sheet))

---

<div style="background-color: #F5F5F5; padding: 20px; border-radius: 10px; text-align: center; margin: 30px 0;">
    <p style="font-size: 14px; color: #666; margin: 0;">
        📝 <strong>Bu notebook'u kaydedip tekrar tekrar kullanabilirsiniz!</strong><br/>
        💡 Kendi projelerinizde bu sorguları referans olarak kullanın.<br/>
        🚀 SQL yolculuğunuzda başarılar dileriz!
    </p>
</div>